/**
 * The generated animated icons. Each entry takes a glyph from
 * registry/icons/index.tsx and moves some of its subpaths (0-based, in the
 * order they appear in the glyph's `d`); every subpath not named stays
 * still. Motions come from ./motion-presets.mjs.
 *
 *   a(glyph, description, label, parts, extra)
 *   part: [name, [subpath indices] | "*", motion | [motion, ...args], { delay, origin, duration }?]
 *
 * `label` finishes the usage snippet shown on rhsui.com; `loop: true` shows
 * it as a looping status line instead of inside a button.
 */
const a = (glyph, description, label, parts, extra = {}) => ({ glyph, description, label, parts, ...extra });
const stagger = (name, indices, motion, gap = 90, start = 0) => indices.map((index, i) => [`${name}-${i + 1}`, [index], motion, { delay: start + i * gap }]);

export const ICONS = [
  // Arrows & direction
  a("IconArrowLeft", "The arrow steps back and returns. For back links and previous steps.", "Back", [["arrow", [0, 1], ["nudge", -2.5, 0]]]),
  a("IconArrowUp", "The arrow lifts and settles. For scroll to top and sort ascending.", "Back to top", [["arrow", [0, 1], ["nudge", 0, -2.5]]]),
  a("IconArrowDown", "The arrow drops and settles. For scroll cues and sort descending.", "Scroll down", [["arrow", [0, 1], ["nudge", 0, 2.5]]]),
  a("IconArrowUpRight", "The arrow reaches out diagonally. For links that leave the page.", "Open", [["arrow", [0, 1], ["nudge", 2, -2]]]),
  a("IconArrowDownLeft", "The arrow comes in diagonally. For incoming transfers and imports.", "Received", [["arrow", [0, 1], ["nudge", -2, 2]]]),
  a("IconArrowDownRight", "The arrow slides down and out. For trends and next rows.", "Details", [["arrow", [0, 1], ["nudge", 2, 2]]]),
  a("IconArrowUpLeft", "The arrow backs up diagonally. For returning to a parent.", "Up one level", [["arrow", [0, 1], ["nudge", -2, -2]]]),
  a("IconArrowLeftRight", "The two arrows pass each other. For swapping and exchanges.", "Swap", [["right", [0, 1], ["nudge", 2, 0]], ["left", [2, 3], ["nudge", -2, 0]]]),
  a("IconArrowCircleRight", "The arrow inside the ring moves on. For continue and next.", "Continue", [["arrow", [1, 2], ["nudge", 2, 0]]]),
  a("IconArrowCircleDown", "The arrow inside the ring drops. For scroll cues and downloads.", "See more", [["arrow", [1, 2], ["nudge", 0, 2]]]),
  a("IconChevronRight", "The chevron leans forward. For rows and menu items that open.", "Next", [["chevron", [0], ["nudge", 2, 0]]]),
  a("IconChevronLeft", "The chevron leans back. For previous and collapse.", "Previous", [["chevron", [0], ["nudge", -2, 0]]]),
  a("IconChevronDown", "The chevron dips. For dropdowns and expandable sections.", "More options", [["chevron", [0], ["nudge", 0, 2]]]),
  a("IconChevronUp", "The chevron rises. For collapse and back to top.", "Collapse", [["chevron", [0], ["nudge", 0, -2]]]),
  a("IconChevronsRight", "Two chevrons move one after the other. For skip ahead and fast forward.", "Skip", stagger("chevron", [0, 1], ["nudge", 2, 0], 80)),
  a("IconChevronsLeft", "Two chevrons step back one after the other. For first page and rewind.", "First page", stagger("chevron", [1, 0], ["nudge", -2, 0], 80)),
  a("IconChevronsDown", "Two chevrons fall one after the other. For expand all and scroll cues.", "Expand all", stagger("chevron", [0, 1], ["nudge", 0, 2], 80)),
  a("IconChevronsUp", "Two chevrons rise one after the other. For collapse all.", "Collapse all", stagger("chevron", [1, 0], ["nudge", 0, -2], 80)),
  a("IconChevronsUpDown", "The chevrons part and close. For selects and sortable columns.", "Sort", [["up", [0], ["nudge", 0, -1.5]], ["down", [1], ["nudge", 0, 1.5]]]),
  a("IconCornerDownRight", "The branch pushes forward. For nested replies and sub-items.", "Reply in thread", [["corner", [0, 1], ["nudge", 1.5, 0]]]),
  a("IconCornerUpLeft", "The turn steps back. For reverting to an earlier level.", "Go back", [["corner", [0, 1], ["nudge", -2, 0]]]),
  a("IconReturn", "The return key swings back. For submit on Enter.", "Submit", [["return", [0, 1], ["nudge", -2, 0]]]),
  a("IconUndo", "The arrow turns back. For undo in editors.", "Undo", [["undo", [0, 1], ["tilt", -18, "50% 50%"]]]),
  a("IconRedo", "The arrow turns forward. For redo in editors.", "Redo", [["redo", [0, 1], ["tilt", 18, "50% 50%"]]]),
  a("IconRotateCcw", "The arrow turns a full circle backwards. For reset and restore.", "Reset", [["ring", [0, 1], ["spin", -360]]]),
  a("IconRepeat", "The two arrows run their loop. For repeat and subscriptions.", "Repeat", [["top", [0, 1], ["nudge", 2, 0]], ["bottom", [2, 3], ["nudge", -2, 0]]]),
  a("IconShuffle", "The crossing lines push their arrows out. For shuffle and random.", "Shuffle", [["heads", [1, 4], ["nudge", 1.5, 0]]]),
  a("IconSort", "One arrow rises while the other falls. For sort controls.", "Sort", [["up", [0, 1], ["nudge", 0, -1.5]], ["down", [2, 3], ["nudge", 0, 1.5]]]),
  a("IconMove", "The arrows breathe outwards. For drag handles and repositioning.", "Move", [["arrows", [0, 1, 2, 3, 4, 5], ["pop", 1.12]]]),
  a("IconMaximize", "The corners reach outwards. For fullscreen and expand.", "Fullscreen", [["out-a", [0, 2], ["nudge", 1.5, -1.5]], ["out-b", [1, 3], ["nudge", -1.5, 1.5]]]),
  a("IconMinimize", "The corners pull inwards. For exit fullscreen.", "Exit fullscreen", [["in-a", [0, 3], ["nudge", 1.5, -1.5]], ["in-b", [1, 2], ["nudge", -1.5, 1.5]]]),
  a("IconTrendUp", "The line climbs as it is drawn. For growth and positive change.", "Growth", [["line", [0], "draw"], ["head", [1], "draw", { delay: 380, duration: 300 }]]),
  a("IconTrendDown", "The line falls as it is drawn. For decline and losses.", "Decline", [["line", [0], "draw"], ["head", [1], "draw", { delay: 380, duration: 300 }]]),
  a("IconCursor", "The pointer clicks. For interactive demos and click targets.", "Click to try", [["pointer", [0, 1], "press"]]),

  // Navigation
  a("IconHome", "The house hops. For home links and dashboards.", "Home", [["house", [0], ["bounce", 2]]]),
  a("IconSidebar", "The panel divider slides. For toggling a sidebar.", "Toggle sidebar", [["divider", [1], ["nudge", -2, 0]]]),
  a("IconSidebarRight", "The inspector divider slides. For toggling a right panel.", "Toggle inspector", [["divider", [1], ["nudge", 2, 0]]]),
  a("IconPanelBottom", "The bottom panel rises. For consoles and docks.", "Toggle console", [["divider", [1], ["nudge", 0, -2]]]),
  a("IconGrid", "The tiles pop one after another. For grid views and app launchers.", "Grid view", stagger("tile", [0, 1, 3, 2], ["pop", 1.15], 70)),
  a("IconDashboard", "The widgets pop one after another. For dashboards and overviews.", "Dashboard", stagger("tile", [0, 1, 2, 3], ["pop", 1.12], 70)),
  a("IconList", "The rows draw in one by one. For list views.", "List view", stagger("row", [0, 1, 2], ["draw", 420], 90)),
  a("IconSearch", "The lens looks left and right. For search in toolbars.", "Search", [["lens", [0, 1], ["wiggle", 12]]], { slug: "search-look" }),
  a("IconFilter", "The funnel shakes its contents through. For filter panels.", "Filters", [["funnel", [0], ["wiggle", 8]]]),
  a("IconExternal", "The arrow leaves the box. For links that open a new tab.", "Open in new tab", [["arrow", [0, 1], ["nudge", 1.5, -1.5]]]),
  a("IconLogIn", "The arrow goes in through the door. For sign in.", "Sign in", [["arrow", [1, 2], ["nudge", 2, 0]]]),
  a("IconMap", "The folded map sways. For maps and directions.", "View map", [["map", [0, 1, 2], ["wiggle", 6]]]),
  a("IconPin", "The pin drops onto the map. For locations and addresses.", "Our location", [["pin", [0, 1], ["bounce", 3]]]),
  a("IconNavigation", "The arrow launches forward. For directions and live location.", "Directions", [["arrow", [0], ["nudge", 2, -2]]]),
  a("IconLocate", "The crosshair tightens on its target. For current location.", "Use my location", [["cross", [0, 1, 2, 3, 4], ["pop", 1.12]], ["dot", [5], "pulse", { delay: 120 }]]),
  a("IconCompass", "The needle swings and settles. For explore and discover.", "Explore", [["needle", [1], ["wiggle", 30]]]),
  a("IconGlobe", "The globe turns on its axis. For language and region pickers.", "Language", [["meridian", [2], "flip"]]),
  a("IconSitemap", "The branches draw from the root. For site structure and org charts.", "Structure", [["links", [3, 4], ["draw", 520]], ...stagger("node", [1, 2], "reveal", 90, 360)]),

  // Actions
  a("IconCheck", "The tick draws itself. For done, saved and confirmed.", "Done", [["tick", [0], "draw"]], { slug: "check-draw" }),
  a("IconClose", "The cross draws stroke by stroke. For dismiss and close.", "Close", stagger("stroke", [0, 1], ["draw", 360], 140)),
  a("IconPlusCircle", "The plus turns a quarter inside its ring. For add actions.", "Add", [["plus", [1, 2], ["spin", 90]]]),
  a("IconMinus", "The line draws across. For remove and decrease.", "Remove", [["line", [0], ["draw", 420]]]),
  a("IconMinusCircle", "The line draws across its ring. For remove.", "Remove", [["line", [1], ["draw", 420]]]),
  a("IconEdit", "The pencil scribbles. For edit buttons.", "Edit", [["pencil", [0, 1], ["wiggle", 8]]]),
  a("IconSave", "The disk presses in. For save.", "Save", [["disk", [0, 1, 2], "press"]]),
  a("IconShare", "The arrow lifts out of the tray. For share sheets.", "Share", [["arrow", [0, 1], ["nudge", 0, -2]]]),
  a("IconLink", "The links pull together. For copy link and attach URL.", "Copy link", [["left", [0], ["nudge", 1, -1]], ["right", [1], ["nudge", -1, 1]]]),
  a("IconFlag", "The flag flutters on its pole. For report and milestones.", "Report", [["cloth", [1], "flutter"]]),
  a("IconThumbsUp", "The thumb tips up. For like and helpful.", "Helpful", [["thumb", [0, 1], ["tilt", -14, "0% 100%"]]]),
  a("IconThumbsDown", "The thumb tips down. For dislike and not helpful.", "Not helpful", [["thumb", [0, 1], ["tilt", -14, "100% 0%"]]]),
  a("IconZoomIn", "The plus grows inside the lens. For zoom in.", "Zoom in", [["plus", [2, 3], ["pop", 1.3]]]),
  a("IconZoomOut", "The minus shrinks inside the lens. For zoom out.", "Zoom out", [["minus", [2], "press"]]),
  a("IconMoreHorizontal", "The dots hop in a wave. For overflow menus.", "More", stagger("dot", [0, 1, 2], ["bounce", 2], 90)),
  a("IconMoreVertical", "The dots pop in turn. For overflow menus in rows.", "More", stagger("dot", [0, 1, 2], ["pop", 1.4], 90)),
  a("IconSliders", "The knobs slide along their tracks. For settings and filters.", "Adjust", [["knob-1", [3], ["nudge", 4, 0]], ["knob-2", [4], ["nudge", -4, 0], { delay: 80 }], ["knob-3", [5], ["nudge", 3, 0], { delay: 160 }]]),
  a("IconScissors", "The blades snip. For cut and trim.", "Cut", [["blade-a", [2], ["tilt", 7, "0% 100%"]], ["blade-b", [3], ["tilt", -7, "0% 0%"]]]),
  a("IconPushpin", "The pin presses down. For pin to top.", "Pin", [["pin", [0, 1, 2], ["bounce", 2]]]),
  a("IconCrop", "The crop frame snaps. For crop tools.", "Crop", [["frame", [0, 1], "press"]]),
  a("IconEraser", "The eraser rubs. For clear and erase.", "Clear", [["eraser", [1, 2], "rub"]]),
  a("IconWand", "The wand flicks and the sparks appear. For magic and AI actions.", "Generate", [["wand", [0, 1], ["tilt", -10, "0% 100%"]], ...stagger("spark", [2, 4, 6], "reveal", 90, 180).map(([name, [i], motion, options]) => [name, [i, i + 1], motion, options])]),
  a("IconMagnet", "The magnet pulls. For attract, snap and leads.", "Attract", [["magnet", [0, 1, 2], ["bounce", 2]]]),
  a("IconToggleLeft", "The knob slides and returns. For switch settings.", "Toggle", [["knob", [1], ["nudge", 3, 0]]]),
  a("IconToggleRight", "The knob slides and returns. For switch settings.", "Toggle", [["knob", [1], ["nudge", -3, 0]]]),
  a("IconCheckSquare", "The tick draws in its box. For task done.", "Mark done", [["tick", [1], "draw"]]),
  a("IconCheckDouble", "Two ticks draw in turn. For read receipts.", "Read", stagger("tick", [0, 1], ["draw", 420], 180)),
  a("IconSettings", "The gear turns a quarter. For settings in dense toolbars.", "Settings", [["gear", [0, 1], ["spin", 90]]], { slug: "settings-turn" }),

  // Status & time
  a("IconInfo", "The i hops. For information and tips.", "About this", [["letter", [1, 2], ["bounce", 2]]]),
  a("IconWarning", "The triangle shakes. For warnings.", "Check this", [["sign", [0, 1, 2], "shake"]]),
  a("IconAlertCircle", "The exclamation mark shakes. For errors that need attention.", "Needs attention", [["mark", [1, 2], "shake"]]),
  a("IconXCircle", "The cross draws inside its ring. For failed and cancelled.", "Failed", stagger("stroke", [1, 2], ["draw", 360], 140)),
  a("IconHelp", "The question mark tilts, puzzled. For help and support.", "Help", [["mark", [1, 2], ["wiggle", 12]]]),
  a("IconZap", "The bolt flickers. For instant, fast and power features.", "Instant", [["bolt", [0], "flash"]]),
  a("IconActivity", "The pulse line draws across. For activity and health checks.", "Live activity", [["line", [0], ["draw", 900]]], { loop: true }),
  a("IconGauge", "The needle sweeps and settles. For performance and speed.", "Performance", [["needle", [1], ["tilt", -70, "0% 100%"]]]),
  a("IconTarget", "The rings ripple from the centre. For goals and focus.", "Goals", [["centre", [2], ["pop", 1.4]], ["middle", [1], ["pop", 1.12], { delay: 110 }]]),
  a("IconTrophy", "The cup jumps. For wins and achievements.", "Achievements", [["cup", [0, 1, 2, 3, 4], ["bounce", 3]]]),
  a("IconRocket", "The rocket lifts off and lands. For launches.", "Launch", [["rocket", [0, 1, 2, 3], ["bounce", 3.5]]]),
  a("IconIdea", "The bulb flickers on. For tips and ideas.", "Tip", [["bulb", [0], "flash"]]),
  a("IconBellOff", "The muted bell gives a small shake. For muted notifications.", "Muted", [["bell", [0, 1, 2, 3], ["wiggle", 8]]]),
  a("IconCalendar", "The rings of the calendar hop. For dates and scheduling.", "Pick a date", stagger("ring", [2, 3], ["bounce", 1.5], 90)),
  a("IconCalendarCheck", "The tick draws on the calendar. For booked and confirmed.", "Booked", [["tick", [4], "draw"]]),
  a("IconCalendarPlus", "The plus pops on the calendar. For add event.", "Add to calendar", [["plus", [4, 5], ["pop", 1.3]]]),
  a("IconHistory", "The ring turns back once. For history and recent.", "History", [["ring", [0, 1], ["spin", -360]]]),
  a("IconLoader", "The spokes turn. For loading states.", "Loading", [["spokes", [0, 1, 2, 3, 4, 5], ["spin", 360]]], { loop: true, pause: 0 }),
  a("IconHourglass", "The hourglass turns over. For waiting and pending.", "Waiting", [["glass", [0, 1, 2, 3], ["spin", 180]]], { loop: true, pause: 900 }),
  a("IconTimer", "The hand sweeps a full turn. For timers and countdowns.", "Timer running", [["hand", [2], ["spin", 360, "50% 100%"]]], { loop: true, pause: 200 }),
  a("IconAlarm", "The alarm rattles. For reminders and wake-ups.", "Reminder", [["clock", [0, 1, 2, 3], "shake"]]),
  a("IconBadgeCheck", "The seal turns a notch and the tick draws. For verified.", "Verified", [["seal", [0], ["spin", 30]], ["tick", [1], "draw", { delay: 200 }]]),
  a("IconCircleDot", "The dot pulses. For live and recording.", "Live", [["dot", [1], ["pulse", 1.3]]], { loop: true }),
  a("IconFlame", "The flame licks. For trending and streaks.", "Trending", [["flame", [0], "flicker"]], { loop: true, pause: 200 }),
  a("IconMedal", "The medal swings on its ribbon. For rewards.", "Rewards", [["medal", [0, 1, 2, 3], ["swing", 10]]]),
  a("IconCrown", "The crown pops. For premium and top rank.", "Premium", [["crown", [0, 1], ["pop", 1.15]]]),
  a("IconSignal", "The bars rise one by one. For strength and levels.", "Signal", stagger("bar", [0, 1, 2, 3], ["grow", "y", "50% 100%"], 80)),
  a("IconBan", "The slash draws across. For blocked and not allowed.", "Blocked", [["slash", [1], ["draw", 420]]]),

  // People & access
  a("IconUser", "The head nods. For account and profile.", "Account", [["head", [0], ["bounce", 1.5]]]),
  a("IconUsers", "The second person steps in. For teams and members.", "Team", [["second", [2, 3], ["nudge", -1.5, 0]]]),
  a("IconUserPlus", "The plus pops. For invite.", "Invite", [["plus", [2, 3], ["pop", 1.3]]]),
  a("IconUserCheck", "The tick draws. For approved members.", "Approved", [["tick", [2], "draw"]]),
  a("IconUserMinus", "The minus draws. For remove member.", "Remove member", [["minus", [2], ["draw", 400]]]),
  a("IconUserX", "The cross draws. For block or remove.", "Block", stagger("stroke", [2, 3], ["draw", 320], 120)),
  a("IconUserCircle", "The person nods in the ring. For account menus.", "Account", [["person", [1, 2], ["bounce", 1.5]]]),
  a("IconIdCard", "The details write themselves on the card. For identity.", "Verify identity", stagger("line", [3, 4], ["draw", 420], 120)),
  a("IconScan", "The frame focuses on the face. For face ID and scanning.", "Scan", [["frame", [0, 1, 2, 3], "press"]]),
  a("IconKey", "The key turns. For API keys and access.", "API keys", [["key", [0, 1, 2, 3], ["tilt", -25, "20% 80%"]]]),
  a("IconShield", "The shield pops. For security.", "Security", [["shield", [0], ["pop", 1.12]]]),
  a("IconShieldCheck", "The tick draws on the shield. For protected.", "Protected", [["tick", [1], "draw"]]),
  a("IconShieldAlert", "The exclamation shakes on the shield. For risks.", "Risk", [["mark", [1, 2], "shake"]]),
  a("IconShieldX", "The cross draws on the shield. For unprotected.", "Unprotected", stagger("stroke", [1, 2], ["draw", 320], 120)),
  a("IconFingerprint", "The ridges draw one after another. For biometric sign-in.", "Touch ID", stagger("ridge", [0, 1, 2, 3], ["draw", 520], 90)),
  a("IconBuilding", "The windows light up in turn. For companies and offices.", "Company", stagger("window", [1, 2, 3, 4, 5, 6], "reveal", 60)),
  a("IconSmile", "The face gives a happy wiggle. For positive feedback.", "Great", [["face", [0, 1, 2, 3], ["wiggle", 10]]]),
  a("IconMeh", "The face shrugs. For neutral feedback.", "Okay", [["mouth", [1], ["nudge", 1.5, 0]]]),
  a("IconFrown", "The face droops. For negative feedback.", "Not great", [["mouth", [1], ["nudge", 0, 1]]]),

  // Communication
  a("IconMailOpen", "The open envelope hops. For read mail and newsletters.", "Newsletter", [["envelope", [0, 1], ["bounce", 2]]]),
  a("IconSend", "The plane flies out and back in. For sending in tight spots.", "Send", [["plane", [0, 1], ["through", 5, -5]]], { slug: "send-fly" }),
  a("IconReply", "The arrow swings back. For reply.", "Reply", [["arrow", [0, 1], ["nudge", -2, 0]]]),
  a("IconAtSign", "The at sign spins. For mentions.", "Mention", [["at", [0, 1], ["spin", 360]]]),
  a("IconMegaphone", "The megaphone calls out. For announcements.", "Announce", [["horn", [0], ["tilt", -8, "0% 50%"]], ["sound", [1], "pulse"]]),
  a("IconHeadphones", "The headphones bob to the beat. For support and audio.", "Support", [["set", [0, 1, 2, 3], ["bounce", 1.5]]]),
  a("IconInbox", "The tray bounces. For inboxes.", "Inbox", [["tray", [0, 1, 2], ["bounce", 2]]]),
  a("IconArchive", "The lid lifts. For archive.", "Archive", [["lid", [0], ["nudge", 0, -2]]]),
  a("IconMessageText", "The lines write themselves in the bubble. For comments.", "Comment", stagger("line", [1, 2], ["draw", 420], 120)),
  a("IconMessages", "The bubbles take turns. For conversations.", "Messages", [["front", [0], ["bounce", 1.5]], ["back", [1], ["bounce", 1.5], { delay: 160 }]]),
  a("IconMessageCircle", "The bubble pops up. For chat.", "Chat", [["bubble", [0], ["pop", 1.12]]]),
  a("IconPhoneCall", "The phone rings and the waves appear. For incoming calls.", "Call", [["phone", [0], "shake"], ...stagger("wave", [2, 1], "reveal", 110, 100)]),
  a("IconVoicemail", "The reels turn. For voicemail.", "Voicemail", stagger("reel", [0, 1], ["pop", 1.2], 120)),
  a("IconRss", "The waves spread from the dot. For feeds.", "Subscribe", stagger("wave", [0, 1], "reveal", 120, 60)),
  a("IconBroadcast", "The signal spreads from the mast. For live streams.", "Go live", stagger("wave", [3, 4], "reveal", 130), { loop: true }),
  a("IconNodes", "The nodes pop in turn. For sharing and networks.", "Share", stagger("node", [0, 1, 2], ["pop", 1.25], 90)),
  a("IconLanguage", "The characters swap places. For translation.", "Translate", [["latin", [4, 5], ["nudge", -1, 0]], ["other", [0, 1, 2, 3], ["nudge", 1, 0]]]),

  // Files & documents
  a("IconFile", "The page pops. For files.", "File", [["page", [0, 1], ["pop", 1.1]]]),
  a("IconFileText", "The lines write themselves. For documents.", "Document", stagger("line", [2, 3], ["draw", 420], 120)),
  a("IconFilePlus", "The plus pops on the page. For new document.", "New document", [["plus", [2, 3], ["pop", 1.3]]]),
  a("IconFileCheck", "The tick draws on the page. For approved documents.", "Approved", [["tick", [2], "draw"]]),
  a("IconFileCode", "The brackets open. For source files.", "Source", [["left", [2], ["nudge", -1.5, 0]], ["right", [3], ["nudge", 1.5, 0]]]),
  a("IconFileImage", "The landscape draws on the page. For image files.", "Image", [["hills", [2], ["draw", 520]]]),
  a("IconFileSheet", "The sheet pops. For spreadsheets and exports.", "Export CSV", [["sheet", [2, 3, 4], ["pop", 1.12]]]),
  a("IconFileMinus", "The minus draws on the page. For remove document.", "Remove", [["minus", [2], ["draw", 400]]]),
  a("IconFileX", "The cross draws on the page. For invalid files.", "Invalid file", stagger("stroke", [2, 3], ["draw", 320], 120)),
  a("IconFileDownload", "The arrow drops through the page. For downloads.", "Download", [["arrow", [2, 3], ["through", 0, 5]]]),
  a("IconFiles", "The front page slides forward. For multiple files.", "Files", [["front", [0, 1], ["nudge", 1, -1]]]),
  a("IconFolder", "The folder hops. For folders.", "Folder", [["folder", [0], ["bounce", 2]]]),
  a("IconFolderPlus", "The plus pops in the folder. For new folder.", "New folder", [["plus", [1, 2], ["pop", 1.3]]]),
  a("IconClipboard", "The clip presses. For paste.", "Paste", [["clip", [1], "press"]]),
  a("IconClipboardCheck", "The tick draws on the clipboard. For completed tasks.", "Completed", [["tick", [2], "draw"]]),
  a("IconClipboardList", "The list writes itself. For agendas.", "Agenda", stagger("line", [2, 3], ["draw", 420], 120)),
  a("IconPaperclip", "The clip wiggles. For attachments.", "Attach", [["clip", [0], ["wiggle", 10]]]),
  a("IconBook", "The book tilts open. For documentation.", "Docs", [["book", [0, 1, 2], ["tilt", -8, "50% 100%"]]]),
  a("IconBookOpen", "The pages flutter. For guides and reading.", "Read the guide", [["book", [0, 1], "flip"]]),
  a("IconNotebook", "The notebook tilts. For notes.", "Notes", [["book", [0, 1, 2, 3, 4, 5], ["tilt", -8, "50% 100%"]]]),
  a("IconNewspaper", "The paper unfolds. For news and blogs.", "News", [["paper", [0, 1, 2, 3, 4], ["pop", 1.1]]]),
  a("IconNote", "The corner of the note lifts. For sticky notes.", "Add note", [["corner", [1], ["pop", 1.3]]]),
  a("IconImage", "The landscape draws. For images.", "Add image", [["hills", [1], ["draw", 520]], ["sun", [2], "reveal", { delay: 300 }]]),
  a("IconPrinter", "The page comes out. For print.", "Print", [["page", [2], ["nudge", 0, 1.5]]]),

  // Media
  a("IconStop", "The square presses. For stop.", "Stop", [["square", [0], "press"]]),
  a("IconSkipBack", "The track jumps back. For previous track.", "Previous", [["track", [0, 1], ["nudge", -2, 0]]]),
  a("IconSkipForward", "The track jumps ahead. For next track.", "Next", [["track", [0, 1], ["nudge", 2, 0]]]),
  a("IconRewind", "The arrows rewind in turn. For seek back.", "Back 10 s", stagger("arrow", [0, 1], ["nudge", -2, 0], 80)),
  a("IconFastForward", "The arrows run ahead in turn. For seek forward.", "Forward 10 s", stagger("arrow", [1, 0], ["nudge", 2, 0], 80)),
  a("IconVolume", "The sound waves reach out. For volume and unmute.", "Sound on", stagger("wave", [1, 2], "reveal", 120)),
  a("IconVolumeLow", "The wave reaches out. For low volume.", "Volume", [["wave", [1], "reveal"]]),
  a("IconVolumeOff", "The cross shakes. For muted.", "Muted", [["cross", [1, 2], "shake"]]),
  a("IconMic", "The microphone pulses. For voice input.", "Voice input", [["capsule", [0], "pulse"]], { loop: true }),
  a("IconCamera", "The shutter clicks. For photo capture.", "Take photo", [["lens", [1], "blink"]]),
  a("IconVideo", "The lens pulses. For video calls.", "Start video", [["lens", [1], "pulse"]]),
  a("IconMusic", "The notes bounce to the beat. For music and audio.", "Now playing", [["note-a", [1], ["bounce", 2]], ["note-b", [2], ["bounce", 2], { delay: 140 }]], { loop: true }),
  a("IconRadio", "The antenna sways. For radio and broadcasts.", "Listen live", [["antenna", [1], ["sway", 8, "0% 100%"]], ["dial", [2], ["spin", 180]]]),
  a("IconFilm", "The film strip pops. For movies.", "Watch", [["strip", "*", ["pop", 1.08]]]),
  a("IconDisc", "The disc spins. For albums and playback.", "Playing", [["disc", [0, 1], ["spin", 360]]], { loop: true, pause: 0 }),
  a("IconCast", "The signal waves reach the screen. For casting.", "Cast", stagger("wave", [3, 2, 1], "reveal", 110)),
  a("IconPodcast", "The waves spread around the mic. For podcasts.", "Listen", stagger("wave", [2, 3], "reveal", 120)),
  a("IconSubtitles", "The captions write themselves. For subtitles.", "Captions", stagger("line", [1, 2, 3, 4], ["draw", 300], 80)),
  a("IconGamepad", "The controller rumbles. For games.", "Play", [["pad", [0, 1, 2, 3, 4], "shake"]]),

  // Devices & theme
  a("IconMonitor", "The screen pops. For desktop.", "Desktop", [["screen", [0], ["pop", 1.08]]]),
  a("IconLaptop", "The lid opens. For laptops.", "Laptop", [["lid", [0], ["grow", "y", "50% 100%"]]]),
  a("IconSmartphone", "The phone buzzes. For mobile and notifications.", "Mobile", [["phone", [0, 1], "shake"]]),
  a("IconTablet", "The tablet tilts. For tablets.", "Tablet", [["tablet", [0, 1], ["tilt", -10, "50% 50%"]]]),
  a("IconWatch", "The hand turns. For wearables and time.", "Watch", [["hand", [3], ["spin", 360, "0% 62%"]]]),
  a("IconKeyboard", "The keys press in turn. For shortcuts.", "Shortcuts", stagger("key", [1, 2, 3, 4], "press", 70)),
  a("IconMouse", "The wheel scrolls. For scroll hints.", "Scroll", [["wheel", [1], ["through", 0, 2]]]),
  a("IconCpu", "The core pulses. For processing and compute.", "Processing", [["core", [1], "pulse"]], { loop: true }),
  a("IconHardDrive", "The lights blink. For storage.", "Storage", stagger("led", [2, 3], "flash", 120)),
  a("IconServer", "The lights blink in turn. For servers and infrastructure.", "Servers", stagger("led", [2, 3], "flash", 160), { loop: true }),
  a("IconWifi", "The signal grows from the dot. For connection.", "Connected", stagger("arc", [2, 1, 0], "reveal", 110)),
  a("IconWifiOff", "The crossed signal shakes. For offline.", "Offline", [["signal", [0, 1, 2, 3, 4, 5, 6], "shake"]]),
  a("IconBluetooth", "The rune pops. For pairing.", "Pair device", [["rune", [0], ["pop", 1.15]]]),
  a("IconPlug", "The plug pushes in. For integrations.", "Connect", [["plug", [0, 1, 2], ["nudge", 0, -2]]]),
  a("IconBattery", "The charge fills up. For battery and quota.", "Battery", [["charge", [2], ["grow", "x", "0% 50%"]]]),
  a("IconBatteryCharging", "The bolt flickers inside. For charging.", "Charging", [["bolt", [2], "flash"]], { loop: true }),
  a("IconPower", "The switch hops. For power and sign-off.", "Power", [["switch", [0], ["bounce", 2]]]),
  a("IconContrast", "The halves swap. For theme and contrast.", "Contrast", [["disc", [0, 1], ["spin", 180]]]),
  a("IconPalette", "The palette tilts. For colours and themes.", "Theme", [["palette", [0, 1, 2, 3], ["wiggle", 8]]]),
  a("IconTv", "The antenna wobbles. For TV and streaming.", "Watch on TV", [["antenna", [1], ["wiggle", 12]]]),
  a("IconSun", "The rays turn. For light mode.", "Light", [["rays", [1, 2, 3, 4, 5, 6, 7, 8], ["spin", 45]]], { slug: "sun-rays" }),
  a("IconMoon", "The moon rocks. For dark mode and night.", "Dark", [["moon", [0], ["wiggle", 12]]], { slug: "moon-rock" }),

  // Code & data
  a("IconCode", "The brackets open. For code.", "View code", [["left", [0], ["nudge", -1.5, 0]], ["right", [1], ["nudge", 1.5, 0]]]),
  a("IconTerminal", "The cursor blinks. For consoles and CLIs.", "Terminal", [["cursor", [2], "fade"]], { loop: true, pause: 0 }),
  a("IconBraces", "The braces open. For JSON and objects.", "JSON", [["left", [0], ["nudge", -1.5, 0]], ["right", [1], ["nudge", 1.5, 0]]]),
  a("IconGitBranch", "The branch draws out. For branches.", "Branches", [["branch", [4], "draw"]]),
  a("IconGitCommit", "The commit pops on the line. For commits.", "Commits", [["commit", [0], ["pop", 1.3]]]),
  a("IconGitMerge", "The branch merges in. For merges.", "Merge", [["branch", [3], "draw"]]),
  a("IconGitPullRequest", "The arrow brings the change back. For pull requests.", "Pull request", [["arrow", [4, 5], ["nudge", -1.5, 0]]]),
  a("IconBug", "The bug scurries. For bugs and issues.", "Report bug", [["bug", "*", "shake"]]),
  a("IconHash", "The hash tilts. For channels and tags.", "Channels", [["hash", [0, 1, 2, 3], ["wiggle", 8]]]),
  a("IconCube", "The cube wobbles. For 3D and components.", "Components", [["cube", [0, 1, 2, 3], ["wiggle", 8]]]),
  a("IconPackage", "The box bounces. For packages and modules.", "Packages", [["box", [0, 1, 2, 3], ["bounce", 2]]]),
  a("IconLayers", "The layers lift apart. For stacks and layers.", "Layers", [["top", [0], ["nudge", 0, -2]], ["middle", [1], ["nudge", 0, -1]]]),
  a("IconWrench", "The wrench turns. For tools and maintenance.", "Tools", [["wrench", [0], ["wiggle", 14]]]),
  a("IconDatabase", "The stack bounces. For data and storage.", "Database", [["db", [0, 1, 2], ["bounce", 2]]]),
  a("IconCloud", "The cloud drifts. For cloud and hosting.", "Cloud", [["cloud", [0], ["float", 1.5]]]),
  a("IconCloudUpload", "The arrow rises into the cloud. For backups and uploads.", "Back up", [["arrow", [1, 2], ["through", 0, -4]]]),
  a("IconCloudDownload", "The arrow drops from the cloud. For restore and downloads.", "Restore", [["arrow", [1, 2], ["through", 0, 4]]]),
  a("IconChart", "The bars grow in turn. For analytics.", "Analytics", stagger("bar", [1, 2, 3], ["grow", "y", "50% 100%"], 90)),
  a("IconChartBar", "The bars grow in turn. For rankings.", "Ranking", stagger("bar", [1, 2, 3], ["grow", "x", "0% 50%"], 90)),
  a("IconChartLine", "The line draws across. For trends.", "Trends", [["line", [1], "draw"]]),
  a("IconPieChart", "The slice pops out. For share and breakdowns.", "Breakdown", [["slice", [1], ["nudge", 1, -1]]]),
  a("IconFunction", "The f pops. For formulas.", "Formula", [["f", [0, 1], ["pop", 1.15]]]),
  a("IconWorkflow", "The connection draws. For automations.", "Automations", [["link", [2], "draw"], ["target", [1], "reveal", { delay: 380 }]]),
  a("IconPuzzle", "The piece wiggles into place. For plugins.", "Plugins", [["piece", [0], ["wiggle", 8]]]),
  a("IconBot", "The bot blinks. For assistants and agents.", "Assistant", stagger("eye", [3, 4], "blink", 0).concat([["antenna", [1, 2], ["bounce", 1.5]]])),
  a("IconQrCode", "The corners pop in turn. For scan to pay or open.", "Scan", stagger("corner", [0, 1, 2], ["pop", 1.12], 80)),

  // Commerce
  a("IconBag", "The bag bounces. For shopping.", "Shop", [["bag", [0, 1], ["bounce", 2]]]),
  a("IconStore", "The shop pops. For stores.", "Visit store", [["store", [0, 1, 2], ["pop", 1.08]]]),
  a("IconTag", "The tag swings. For prices and labels.", "Price", [["tag", [0, 1], ["tilt", 12, "0% 0%"]]]),
  a("IconPercent", "The percent sign spins. For discounts.", "Sale", [["percent", [0, 1, 2], ["spin", 180]]]),
  a("IconCreditCard", "The card slides. For payments.", "Pay", [["card", [0, 1, 2], ["drive"]]]),
  a("IconBanknote", "The note flips. For cash and payouts.", "Payout", [["note", [0, 1, 2, 3], "flip"]]),
  a("IconWallet", "The clasp pops. For wallets and balance.", "Wallet", [["clasp", [2, 3], ["nudge", 1.5, 0]]]),
  a("IconReceipt", "The lines print. For receipts.", "Receipt", stagger("line", [1, 2, 3], ["draw", 320], 90)),
  a("IconTicket", "The ticket tilts. For events and vouchers.", "Tickets", [["ticket", [0, 1, 2, 3], ["tilt", -10, "50% 50%"]]]),
  a("IconGift", "The gift jumps. For gifts and rewards.", "Gift", [["gift", [0, 1, 2, 3, 4], ["bounce", 3]]]),
  a("IconBarcode", "The bars flash like a scan. For SKUs.", "Scan", stagger("bar", [0, 1, 2, 3, 4, 5, 6, 7], "flash", 40)),
  a("IconTruck", "The truck drives. For shipping.", "Track order", [["truck", [0, 1, 2, 3, 4], ["drive"]]]),
  a("IconCoins", "The top coin drops onto the stack. For balance and credits.", "Credits", [["coin", [3, 4], ["bounce", 2.5]]]),
  a("IconEuro", "The euro flips. For prices in euro.", "Pricing", [["euro", [0, 1, 2], "flip"]]),
  a("IconDollar", "The dollar flips. For prices in dollars.", "Pricing", [["dollar", [0, 1], "flip"]]),
  a("IconPiggyBank", "The pig hops. For savings.", "Savings", [["pig", [0, 1, 2, 3], ["bounce", 2]]]),
  a("IconBasket", "The basket bounces. For groceries.", "Basket", [["basket", [0, 1, 2, 3, 4], ["bounce", 2]]]),
  a("IconScale", "The beam tips and levels. For compare and legal.", "Compare", [["beam", [2, 3, 4], ["tilt", 8, "50% 50%"]]]),
  a("IconBadgePercent", "The seal turns and the percent pops. For deals.", "Deal", [["seal", [0], ["spin", 30]], ["percent", [1, 2, 3], ["pop", 1.2], { delay: 160 }]]),
  a("IconContactless", "The waves spread. For tap to pay.", "Tap to pay", stagger("wave", [3, 0, 1, 2], "reveal", 90)),
  a("IconLandmark", "The bank pops. For banks and institutions.", "Bank", [["bank", [0, 1, 2, 3, 4, 5, 6], ["pop", 1.08]]]),

  // Text & editing
  a("IconText", "The letter pops. For typography.", "Text", [["letter", [0, 1, 2], ["pop", 1.15]]]),
  a("IconBold", "The letter thickens. For bold.", "Bold", [["letter", [0, 1], ["pop", 1.15]]]),
  a("IconItalic", "The letter leans. For italic.", "Italic", [["letter", [0, 1, 2], ["tilt", -10, "50% 50%"]]]),
  a("IconUnderline", "The line draws under. For underline.", "Underline", [["line", [1], ["draw", 420]]]),
  a("IconStrikethrough", "The line strikes through. For strikethrough.", "Strike", [["line", [0], ["draw", 420]]]),
  a("IconAlignLeft", "The short lines grow from the left. For align left.", "Align left", stagger("line", [1, 3], ["grow", "x", "0% 50%"], 90)),
  a("IconAlignCenter", "The short lines grow from the centre. For align centre.", "Align centre", stagger("line", [1, 3], ["grow", "x", "50% 50%"], 90)),
  a("IconAlignRight", "The short lines grow from the right. For align right.", "Align right", stagger("line", [1, 3], ["grow", "x", "100% 50%"], 90)),
  a("IconAlignJustify", "The lines draw in turn. For justify.", "Justify", stagger("line", [0, 1, 2, 3], ["draw", 320], 70)),
  a("IconHeading", "The heading pops. For headings.", "Heading", [["h", [0, 1, 2], ["pop", 1.15]]]),
  a("IconListOrdered", "The lines draw in order. For numbered lists.", "Numbered list", stagger("line", [0, 1, 2], ["draw", 360], 90)),
  a("IconListChecks", "The ticks draw in turn. For checklists.", "Checklist", stagger("tick", [3, 4, 5], ["draw", 300], 110)),
  a("IconIndent", "The marker pushes in. For indent.", "Indent", [["marker", [4], ["nudge", 2, 0]]]),
  a("IconOutdent", "The marker pulls out. For outdent.", "Outdent", [["marker", [4], ["nudge", -2, 0]]]),
  a("IconQuote", "The quote marks pop. For quotes and testimonials.", "Quote", stagger("mark", [0, 1], ["pop", 1.2], 100)),
  a("IconPilcrow", "The mark pops. For paragraphs.", "Paragraph", [["mark", [0, 1, 2], ["pop", 1.15]]]),
  a("IconHighlighter", "The marker draws its line. For highlights.", "Highlight", [["line", [3], ["draw", 480]]]),

  // Weather & nature
  a("IconCloudRain", "Rain falls from the cloud. For weather and forecasts.", "Rain expected", stagger("drop", [1, 2, 3], ["through", 0, 3], 140), { loop: true, pause: 200 }),
  a("IconCloudSnow", "Snow drifts down. For winter weather.", "Snow expected", stagger("flake", [1, 2, 3], ["through", 0, 2.5], 200), { loop: true, pause: 300 }),
  a("IconCloudLightning", "The bolt strikes. For storms.", "Storm warning", [["bolt", [1], "flash"]], { loop: true }),
  a("IconCloudSun", "The cloud drifts past the sun. For mild weather.", "Partly cloudy", [["cloud", [4], ["nudge", 1.5, 0]]]),
  a("IconWind", "The gusts blow in turn. For wind.", "Windy", stagger("gust", [0, 1, 2], ["nudge", 2, 0], 110), { loop: true }),
  a("IconSnowflake", "The snowflake turns. For winter and freeze.", "Freeze", [["flake", [0, 1, 2, 3, 4], ["spin", 60]]]),
  a("IconThermometer", "The mercury rises. For temperature.", "Temperature", [["mercury", [1], ["grow", "y", "50% 100%"]]]),
  a("IconDroplet", "The drop falls and lands. For water and ink.", "Water", [["drop", [0], ["bounce", 2.5]]]),
  a("IconUmbrella", "The umbrella rocks. For rain and cover.", "Covered", [["umbrella", [0, 1, 2], ["sway", 8, "50% 50%"]]]),
  a("IconLeaf", "The leaf sways. For eco and sustainable.", "Sustainable", [["leaf", [0, 1], ["sway", 10, "0% 100%"]]]),
  a("IconTree", "The tree sways. For parks and nature.", "Nature", [["crown", [1], ["sway", 6]]]),
  a("IconFlower", "The flower sways. For spring and gardens.", "Spring", [["flower", [0, 1, 2], ["sway", 8]]]),
  a("IconMountain", "The peak pops. For outdoor and adventure.", "Adventure", [["peaks", [0, 1], ["pop", 1.08]]]),
  a("IconSunrise", "The sun comes up. For mornings.", "Morning", [["arrow", [2, 3], ["nudge", 0, -2]]]),
  a("IconRainbow", "The arcs draw in turn. For colour and pride.", "Colourful", stagger("arc", [0, 1, 2], ["draw", 480], 110)),
  a("IconWaves", "The waves roll. For sea and flow.", "Flow", stagger("wave", [0, 1, 2], ["nudge", 1.5, 0], 120), { loop: true }),
  a("IconPaw", "The toes pop in turn. For pets.", "Pets", stagger("toe", [1, 2, 3, 4], ["pop", 1.3], 70)),
  a("IconSprout", "The sprout grows. For growth and new starts.", "Grow", [["plant", [0, 1, 2], ["grow", "y", "50% 100%"]]]),

  // Travel & places
  a("IconPlane", "The plane climbs. For flights.", "Flights", [["plane", [0], ["float", 2.5]]]),
  a("IconCar", "The car drives. For driving and rentals.", "Drive", [["car", [0, 1, 2, 3, 4, 5], ["drive"]]]),
  a("IconBike", "The bike rolls. For cycling.", "Ride", [["bike", [0, 1, 2, 3, 4, 5], ["drive"]]]),
  a("IconBus", "The bus rumbles. For public transport.", "Bus", [["bus", [0, 1, 2, 3, 4, 5], ["bounce", 1]]]),
  a("IconTrain", "The train rumbles. For rail.", "Train", [["train", [0, 1, 2, 3, 4, 5], ["bounce", 1]]]),
  a("IconShip", "The ship rocks on the water. For shipping and cruises.", "Shipping", [["ship", [0, 1, 2, 3], ["sway", 6]]]),
  a("IconBed", "The bed settles. For hotels and stays.", "Book a stay", [["pillow", [3], ["bounce", 1.5]]]),
  a("IconSuitcase", "The suitcase hops. For trips.", "Trips", [["case", [0, 1, 2, 3], ["bounce", 2]]]),
  a("IconTent", "The tent pops. For camping.", "Camping", [["tent", [0, 1, 2, 3], ["pop", 1.08]]]),
  a("IconCoffee", "The steam rises. For cafes and breaks.", "Coffee break", stagger("steam", [2, 3], "rise", 160), { loop: true }),
  a("IconUtensils", "The cutlery clinks. For restaurants.", "Book a table", [["fork", [0, 1], ["tilt", -8, "50% 100%"]], ["knife", [2], ["tilt", 8, "50% 100%"]]]),
  a("IconParking", "The P pops. For parking.", "Parking", [["p", [1], ["pop", 1.15]]]),
  a("IconSignpost", "The signs point the way. For directions.", "Directions", [["right", [1], ["nudge", 1.5, 0]], ["left", [2], ["nudge", -1.5, 0]]]),
  a("IconFuel", "The pump pops. For fuel and energy.", "Fuel", [["pump", [0, 1, 2, 3], ["pop", 1.08]]]),
  a("IconAnchor", "The anchor swings. For harbours and stability.", "Harbour", [["anchor", [0, 1, 2, 3, 4, 5], ["swing", 10]]]),

  // Health & sport
  a("IconHeartPulse", "The pulse runs through the heart. For health.", "Health", [["pulse", [1], ["draw", 800]]], { loop: true }),
  a("IconStethoscope", "The stethoscope swings. For checkups.", "Checkup", [["scope", [0, 1, 2], ["swing", 8]]]),
  a("IconPill", "The pill turns. For medicine.", "Medication", [["pill", [0, 1], ["spin", 180]]]),
  a("IconFirstAid", "The cross pulses. For first aid and clinics.", "First aid", [["cross", [1, 2], "pulse"]]),
  a("IconDumbbell", "The weight lifts. For workouts.", "Workout", [["weight", [0, 1, 2, 3, 4], ["bounce", 2.5]]]),
  a("IconBall", "The ball bounces and turns. For sport.", "Match day", [["ball", [0, 1, 2, 3, 4, 5, 6], ["toss"]]]),
  a("IconApple", "The apple wiggles. For nutrition.", "Nutrition", [["apple", [0, 1], ["wiggle", 8]]]),
  a("IconHospital", "The cross pulses. For hospitals.", "Hospital", [["cross", [2, 3], "pulse"]]),
  a("IconAccessibility", "The figure waves. For accessibility.", "Accessibility", [["figure", [0, 1, 2, 3, 4], ["bounce", 1.5]]]),
  a("IconHeart", "The heart beats twice. For health and favourites.", "Favourite", [["heart", [0], "beat"]], { slug: "heart-beat" }),

  // Learning & work
  a("IconGraduationCap", "The cap is tossed. For courses and graduation.", "Courses", [["cap", [0, 1, 2], ["toss"]]]),
  a("IconBriefcase", "The briefcase hops. For jobs and business.", "Careers", [["case", [0, 1, 2], ["bounce", 2]]]),
  a("IconPresentation", "The board pops. For presentations.", "Present", [["board", [0, 1], ["pop", 1.08]]]),
  a("IconLibrary", "The leaning book tips. For libraries.", "Library", [["book", [2], ["tilt", 10, "50% 100%"]]]),
  a("IconCalculator", "The keys press in turn. For calculations.", "Calculate", stagger("key", [2, 3, 4, 5, 6, 7], "press", 60)),
  a("IconRuler", "The marks draw along the ruler. For measuring.", "Measure", stagger("mark", [1, 2, 3], ["draw", 260], 90)),
  a("IconAward", "The rosette swings. For awards.", "Awards", [["award", [0, 1], ["swing", 10]]]),
  a("IconBackpack", "The backpack hops. For school.", "School", [["bag", [0, 1, 2, 3], ["bounce", 2]]]),
  a("IconFlask", "The liquid sloshes. For labs and beta features.", "Beta", [["flask", [0, 1, 2], ["wiggle", 8]]]),
  a("IconGlasses", "The glasses tip. For reading and review.", "Review", [["glasses", [0, 1, 2, 3, 4], ["wiggle", 8]]]),

  // Shapes & layout
  a("IconCircle", "The circle turns. For shapes and loading.", "Ellipse", [["circle", [0], ["spin", 360]]]),
  a("IconSquare", "The square turns a quarter. For shapes.", "Rectangle", [["square", [0], ["spin", 90]]]),
  a("IconTriangle", "The triangle turns a third. For shapes.", "Triangle", [["triangle", [0], ["spin", 120]]]),
  a("IconHexagon", "The hexagon turns a sixth. For shapes.", "Polygon", [["hexagon", [0], ["spin", 60]]]),
  a("IconDiamond", "The diamond turns a quarter. For shapes.", "Diamond", [["diamond", [0], ["spin", 90]]]),
  a("IconShapes", "The shapes pop in turn. For elements panels.", "Elements", stagger("shape", [0, 1, 2], ["pop", 1.2], 90)),
  a("IconFrame", "The frame pops. For artboards.", "Frame", [["frame", [0, 1, 2, 3], ["pop", 1.1]]]),
  a("IconSquareDashed", "The selection pulses. For marquee selection.", "Select area", [["marquee", [0, 1, 2, 3, 4, 5, 6, 7], "pulse"]]),
  a("IconComponent", "The diamonds pop in turn. For components and symbols.", "Components", stagger("diamond", [0, 3, 1, 2], ["pop", 1.3], 70)),
  a("IconSpline", "The curve draws between its handles. For vector paths.", "Pen tool", [["curve", [0], "draw"]]),
  a("IconBrush", "The brush paints. For drawing.", "Brush", [["brush", [0, 1], ["wiggle", 10]]]),
  a("IconPipette", "The pipette dips. For colour picking.", "Pick colour", [["pipette", [0, 1, 2], ["nudge", -1, 1]]]),
];
