// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The alarm rattles. For reminders and wake-ups. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "clock",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1.6px)"
        },
        {
          "transform": "translateX(1.6px)"
        },
        {
          "transform": "translateX(-1.2000000000000002px)"
        },
        {
          "transform": "translateX(1.2000000000000002px)"
        },
        {
          "transform": "translateX(-0.5599999999999999px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconAlarmAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="clock" d="M18.34 10.04A7 7 0 1 1 14.96 6.66M12 9.5V13l2.5 1.5M5 3.5L2.5 6M19 3.5L21.5 6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
