// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The short lines grow from the left. For align left. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line-1",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "0% 50%",
      "keyframes": [
        {
          "transform": "scaleX(0.2)"
        },
        {
          "transform": "scaleX(1)"
        }
      ]
    },
    {
      "part": "line-2",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "0% 50%",
      "keyframes": [
        {
          "transform": "scaleX(0.2)"
        },
        {
          "transform": "scaleX(1)"
        }
      ],
      "delay": 90
    }
  ],
  "pause": 1400
};

export function IconAlignLeftAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 6h16M4 15h16" />
      <path data-part="line-1" d="M4 10.5h10" style={{ transformBox: "fill-box" }} />
      <path data-part="line-2" d="M4 19.5h10" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
