// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The chair rocks. For lounges and seating. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "chair",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(6deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconArmchairAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="chair" d="M6.5 11V7.5a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2V11M4 12a1.5 1.5 0 0 1 3 0v2.5h10V12a1.5 1.5 0 0 1 3 0v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zM6.5 18v2.5M17.5 18v2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
