// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The at sign spins. For mentions. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "at",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconAtSignAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="at" d="M16 12a4 4 0 1 1-4-4M16 8v5.5a2.5 2.5 0 0 0 5 0V12a9 9 0 1 0-3.6 7.2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
