// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cash slides out. For withdrawals. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "cash",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconAtmAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 3H5a2 2 0 0 0-2 2v8h18V6.2M6.5 7h11" />
      <path data-part="cash" d="M7 13v7.5h10V13M10 17h4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
