// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The orbits turn around the nucleus. For science and physics. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "orbits",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconAtomAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M13 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      <path data-part="orbits" d="M20.5 12c0 2.2-3.8 4-8.5 4s-8.5-1.8-8.5-4 3.8-4 8.5-4 8.5 1.8 8.5 4zM16.2 19.4c-1.9 1.1-5.3-1.3-7.6-5.4S5.9 5.7 7.8 4.6s5.3 1.3 7.6 5.4 2.7 8.3.8 9.4zM7.8 19.4c-1.9-1.1-1.5-5.3.8-9.4s5.7-6.5 7.6-5.4 1.5 5.3-.8 9.4-5.7 6.5-7.6 5.4z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
