// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The backpack hops. For school. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bag",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBackpackAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="bag" d="M6 10a5 5 0 0 1 5-5h2a5 5 0 0 1 5 5v9.5a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zM10 5V3.5h4V5M9 20.5v-5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v5M9 11h6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
