// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The seal turns a notch and the tick draws. For verified. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "seal",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(30deg)"
        }
      ]
    },
    {
      "part": "tick",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 200
    }
  ],
  "pause": 1400
};

export function IconBadgeCheckAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="seal" d="M12 3L14.02 4.47L16.5 4.21L17.52 6.48L19.79 7.5L19.53 9.98L21 12L19.53 14.02L19.79 16.5L17.52 17.52L16.5 19.79L14.02 19.53L12 21L9.98 19.53L7.5 19.79L6.48 17.52L4.21 16.5L4.47 14.02L3 12L4.47 9.98L4.21 7.5L6.48 6.48L7.5 4.21L9.98 4.47z" style={{ transformBox: "fill-box" }} />
      <path data-part="tick" d="M8.5 12l2.5 2.5 4.5-5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
