// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The ball bounces and turns. For sport. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "ball",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "translateY(0px) rotate(0deg)"
        },
        {
          "transform": "translateY(-4px) rotate(-14deg)"
        },
        {
          "transform": "translateY(0px) rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBallAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="ball" d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3M12 7.5l3.3 2.4-1.3 3.9h-4l-1.3-3.9zM12 3.5v4M15.3 9.9l4-1.3M14 13.8l2.5 3.4M10 13.8l-2.5 3.4M8.7 9.9l-4-1.3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
