// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The note flips. For cash and payouts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "note",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleX(1)"
        },
        {
          "transform": "scaleX(0.08)"
        },
        {
          "transform": "scaleX(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBanknoteAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="note" d="M17.8 6H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9.2M14.5 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM6 10.5v3M18 10.5v3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
