// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The charge fills up. For battery and quota. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "charge",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "0% 50%",
      "keyframes": [
        {
          "transform": "scaleX(0.2)"
        },
        {
          "transform": "scaleX(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBatteryAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M15.8 8H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h13a1 1 0 0 0 1-1V9.2M21 10.5v3" />
      <path data-part="charge" d="M6 10.5h6v3H6z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
