// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bolt flickers inside. For charging. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bolt",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBatteryChargingAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M15.8 8H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h13a1 1 0 0 0 1-1V9.2M21 10.5v3" />
      <path data-part="bolt" d="M11 9.5l-2 2.5h3l-2 2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
