// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The mug raises a toast. For bars and drinks. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "mug",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "20% 90%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-12deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBeerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="mug" d="M5.5 8h10v10.5a2 2 0 0 1-2 2h-6a2 2 0 0 1-2-2zM15.5 10.5h2a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2h-2M5.5 8a2.5 2.5 0 0 1 2.3-3.8 3 3 0 0 1 5.4 0A2.5 2.5 0 0 1 15.5 8M9 11.5v5.5M12 11.5v5.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
