// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bike rolls. For cycling. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bike",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(2.5px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(-0.8px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBikeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="bike" d="M8.5 16a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zM22.5 16a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zM5 16l3.5-7L12 16l3.5-7L19 16M8.5 9h7M7 9h3M15.5 9l-1-3H13" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
