// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plan draws. For architecture and plans. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plan",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBlueprintAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3.5 5.5a2 2 0 0 1 2-2H20v14H5.5a2 2 0 0 0-2 2zM3.5 19.5a2 2 0 0 0 2 2H20v-4" />
      <path data-part="plan" d="M8 7.5h4v6h5M12 10.5h-4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
