// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The pages flutter. For guides and reading. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "book",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleX(1)"
        },
        {
          "transform": "scaleX(0.08)"
        },
        {
          "transform": "scaleX(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBookOpenAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="book" d="M12 6.5c-1.8-1.6-4.6-2-8.5-2v14c3.9 0 6.7.4 8.5 2 1.8-1.6 4.6-2 8.5-2v-14c-3.9 0-6.7.4-8.5 2zM12 6.5v14" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
