// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bot blinks. For assistants and agents. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "eye-1",
      "duration": 340,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleY(1)"
        },
        {
          "transform": "scaleY(0.1)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "eye-2",
      "duration": 340,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleY(1)"
        },
        {
          "transform": "scaleY(0.1)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "antenna",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-1.5px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.5249999999999999px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBotAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8 8h8a3 3 0 0 1 3 3v5a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3v-5a3 3 0 0 1 3-3zM2.5 12.5v2M21.5 12.5v2" />
      <path data-part="eye-1" d="M9.5 13h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="eye-2" d="M14.5 13h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="antenna" d="M12 8V5M12 4h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
