// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The brain pulses. For thinking and AI. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "brain",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBrainAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="brain" d="M12 5.5a3 3 0 0 0-5.5-1.5A3 3 0 0 0 4 8a3 3 0 0 0 0 5 3 3 0 0 0 2 4.5A3 3 0 0 0 12 19zM12 5.5a3 3 0 0 1 5.5-1.5A3 3 0 0 1 20 8a3 3 0 0 1 0 5 3 3 0 0 1-2 4.5A3 3 0 0 1 12 19zM12 5.5V19M8 9.5c1.3 0 2 .7 2 2M16 9.5c-1.3 0-2 .7-2 2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
