// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The signal spreads from the mast. For live streams. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wave-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "wave-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 130
    }
  ],
  "pause": 1400
};

export function IconBroadcastAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M13 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM12 12v8.5M8 20.5h8" />
      <path data-part="wave-1" d="M8.5 7.5a5 5 0 0 1 7 0" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-2" d="M5.6 4.6a9 9 0 0 1 12.8 0" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
