// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The broom sweeps. For cleaning up. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "broom",
      "duration": 1100,
      "easing": "linear",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-10deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(7.5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-4deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(1.5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBroomAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="broom" d="M15.5 3l-3.5 8M7.5 10.5l8 3.5-2 6.5L4 17zM9 14.5l-1.5 4.5M12 15.5l-1.2 4.2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
