// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bug scurries. For bugs and issues. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bug",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1.6px)"
        },
        {
          "transform": "translateX(1.6px)"
        },
        {
          "transform": "translateX(-1.2000000000000002px)"
        },
        {
          "transform": "translateX(1.2000000000000002px)"
        },
        {
          "transform": "translateX(-0.5599999999999999px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconBugAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="bug" d="M8 8V6.5a4 4 0 0 1 8 0V8M16.8 8H7v5a5 5 0 0 0 10 0V9.2M3.5 11.5h3.5M17 11.5h3.5M4.5 17.5l2.7-1.6M19.5 17.5l-2.7-1.6M5 5.5l2.2 1.7M19 5.5l-2.2 1.7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
