// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The flame flickers. For birthdays and celebrations. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "flame",
      "duration": 820,
      "easing": "linear",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "none",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleY(1.08) skewX(-3deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleY(0.95) skewX(2deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleY(1.04) skewX(-1deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "none",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCakeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4.5 20.5v-7A1.5 1.5 0 0 1 6 12h12a1.5 1.5 0 0 1 1.5 1.5v7M3 20.5h18M4.5 16c1.25.9 2.5.9 3.75 0s2.5-.9 3.75 0 2.5.9 3.75 0 2.5-.9 3.75 0M12 12V8.5" />
      <path data-part="flame" d="M12 6.5c-.8-.8-.8-1.8 0-3 .8 1.2.8 2.2 0 3z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
