// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The keys press in turn. For calculations. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "key-1",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    },
    {
      "part": "key-2",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 60
    },
    {
      "part": "key-3",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 120
    },
    {
      "part": "key-4",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 180
    },
    {
      "part": "key-5",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 240
    },
    {
      "part": "key-6",
      "duration": 420,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.84)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 300
    }
  ],
  "pause": 1400
};

export function IconCalculatorAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M15.8 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6.2M8.5 7h7v3h-7z" />
      <path data-part="key-1" d="M8.5 13.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="key-2" d="M12 13.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="key-3" d="M15.5 13.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="key-4" d="M8.5 17h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="key-5" d="M12 17h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="key-6" d="M15.5 17h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
