// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The shutter clicks. For photo capture. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "lens",
      "duration": 340,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleY(1)"
        },
        {
          "transform": "scaleY(0.1)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCameraAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8 7l1.5-2.5h5L16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2z" />
      <path data-part="lens" d="M15.5 13.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
