// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The car drives. For driving and rentals. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "car",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(2.5px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(-0.8px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCarAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="car" d="M3.5 16.5V13l1.8-4.6A2 2 0 0 1 7.2 7h9.6a2 2 0 0 1 1.9 1.4l1.8 4.6v3.5a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1zM3.5 13h17M6 17.5v2M18 17.5v2M7 15h.01M17 15h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
