// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bars grow in turn. For analytics. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bar-1",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "bar-2",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 90
    },
    {
      "part": "bar-3",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconChartAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 20h16" />
      <path data-part="bar-1" d="M7 16v-6" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-2" d="M12 16V5" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-3" d="M17 16v-3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
