// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The candles grow in turn. For trading charts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "candle-1",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "candle-2",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 90
    },
    {
      "part": "candle-3",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconChartCandlesAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 3.5v3M7 15.5v5M17 6.5v3M17 18v2.5M12 9v2M12 17.5v3" />
      <path data-part="candle-1" d="M5 6.5h4v9H5z" style={{ transformBox: "fill-box" }} />
      <path data-part="candle-2" d="M10 11h4v6.5h-4z" style={{ transformBox: "fill-box" }} />
      <path data-part="candle-3" d="M15 9.5h4V18h-4z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
