// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The shape inside expands. For skills and comparisons. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "shape",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.2)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconChartRadarAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 3l8.5 6.2-3.3 10H6.8L3.5 9.2zM12 3v5M20.5 9.2L16 11M17.2 19.2l-2.7-3.7M6.8 19.2l2.7-3.7M3.5 9.2L8 11" />
      <path data-part="shape" d="M12 8l4 3-1.5 4.5h-5L8 11z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
