// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** Two ticks draw in turn. For read receipts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tick-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "tick-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconCheckDoubleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="tick-1" d="M2.5 12.5L7 17l9.5-10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="tick-2" d="M12.5 16.5l.5.5L22 7" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
