// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hat puffs up. For recipes and kitchens. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hat",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconChefHatAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="hat" d="M7 14.5a4 4 0 1 1 1.5-7.7 4 4 0 0 1 7 0A4 4 0 1 1 17 14.5v5a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1zM7 17h10" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
