// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cherries swing on their stems. For fruit and sweet things. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "cherries",
      "duration": 900,
      "easing": "linear",
      "origin": "50% 0%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(8deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-6.24deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(4deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-1.76deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCherriesAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="cherries" d="M11 17a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zM20 15a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zM7.5 13.5c.5-4.5 3-8 7.5-10M16.5 11.5c-.3-3.5-.7-5.6-1.5-8M15 3.5c1.6-.4 3.6 0 4.6 1.5-1.6.7-3.1.5-4.6-1.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
