// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** Two chevrons rise one after the other. For collapse all. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "chevron-1",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "chevron-2",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 80
    }
  ],
  "pause": 1400
};

export function IconChevronsUpAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="chevron-1" d="M6 11.5l6-6 6 6" style={{ transformBox: "fill-box" }} />
      <path data-part="chevron-2" d="M6 18l6-6 6 6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
