// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The circle turns. For shapes and loading. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "circle",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCircleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="circle" d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
