// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The traces draw. For electronics and hardware. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "trace-1",
      "duration": 320,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "trace-2",
      "duration": 320,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 90
    },
    {
      "part": "trace-3",
      "duration": 320,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconCircuitAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.2M17 8h-2M7.5 8h.01M17 8h.01M7 16h.01" />
      <path data-part="trace-1" d="M7 8h4l2 2v4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="trace-2" d="M7 16h5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="trace-3" d="M15 14v2.5h2" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
