// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cross draws stroke by stroke. For dismiss and close. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "stroke-1",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "stroke-2",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 140
    }
  ],
  "pause": 1400
};

export function IconCloseAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="stroke-1" d="M6 6l12 12" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="stroke-2" d="M18 6L6 18" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
