// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bolt strikes. For storms. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bolt",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCloudLightningAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 15.5a3.5 3.5 0 0 1-.4-6.98A5 5 0 0 1 16.3 7a4.25 4.25 0 0 1 .2 8.5z" />
      <path data-part="bolt" d="M12.5 17l-2 2.5h3l-2 2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
