// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** Rain falls from the cloud. For weather and forecasts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "drop-1",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 3px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -3px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "drop-2",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 3px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -3px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ],
      "delay": 140
    },
    {
      "part": "drop-3",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 3px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -3px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ],
      "delay": 280
    }
  ],
  "pause": 200
};

export function IconCloudRainAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 15.5a3.5 3.5 0 0 1-.4-6.98A5 5 0 0 1 16.3 7a4.25 4.25 0 0 1 .2 8.5z" />
      <path data-part="drop-1" d="M8 18.5l-1 2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-2" d="M12 18.5l-1 2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-3" d="M16 18.5l-1 2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
