// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** Snow drifts down. For winter weather. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "flake-1",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -2.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "flake-2",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -2.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ],
      "delay": 200
    },
    {
      "part": "flake-3",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -2.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ],
      "delay": 400
    }
  ],
  "pause": 300
};

export function IconCloudSnowAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 15.5a3.5 3.5 0 0 1-.4-6.98A5 5 0 0 1 16.3 7a4.25 4.25 0 0 1 .2 8.5z" />
      <path data-part="flake-1" d="M8 19h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="flake-2" d="M12 20.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="flake-3" d="M16 19h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
