// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrow rises into the cloud. For backups and uploads. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -4px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, 4px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCloudUploadAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7.5 18a3.5 3.5 0 0 1-.9-6.9A5 5 0 0 1 16.3 10a4.3 4.3 0 0 1 .7 8" />
      <path data-part="arrow" d="M12 20.5V13M9 15.5l3-3 3 3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
