// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The steam rises. For cafes and breaks. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "steam-1",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "steam-2",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ],
      "delay": 160
    }
  ],
  "pause": 1400
};

export function IconCoffeeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M5 9h12v6a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5zM17 10.5h1.5a2.5 2.5 0 0 1 0 5H17" />
      <path data-part="steam-1" d="M8.5 3.5V6" style={{ transformBox: "fill-box" }} />
      <path data-part="steam-2" d="M12 3.5V6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
