// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The diamonds pop in turn. For components and symbols. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "diamond-1",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    },
    {
      "part": "diamond-2",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 70
    },
    {
      "part": "diamond-3",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 140
    },
    {
      "part": "diamond-4",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 210
    }
  ],
  "pause": 1400
};

export function IconComponentAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="diamond-1" d="M12 3l2.5 2.5L12 8 9.5 5.5z" style={{ transformBox: "fill-box" }} />
      <path data-part="diamond-2" d="M18.5 9.5L21 12l-2.5 2.5L16 12z" style={{ transformBox: "fill-box" }} />
      <path data-part="diamond-3" d="M12 16l2.5 2.5L12 21l-2.5-2.5z" style={{ transformBox: "fill-box" }} />
      <path data-part="diamond-4" d="M5.5 9.5L8 12l-2.5 2.5L3 12z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
