// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The waves spread. For tap to pay. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wave-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "wave-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 90
    },
    {
      "part": "wave-3",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 180
    },
    {
      "part": "wave-4",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 270
    }
  ],
  "pause": 1400
};

export function IconContactlessAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="wave-1" d="M5 10.5a2 2 0 0 1 0 3" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-2" d="M8.5 8a6 6 0 0 1 0 8" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-3" d="M12 5.5a10 10 0 0 1 0 13" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-4" d="M15.5 3a14 14 0 0 1 0 18" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
