// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The core pulses. For processing and compute. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "core",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCpuAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 7h10v10H7zM10 3.5V7M14 3.5V7M10 17v3.5M14 17v3.5M3.5 10H7M3.5 14H7M17 10h3.5M17 14h3.5" />
      <path data-part="core" d="M10 10h4v4h-4z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
