// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hook lowers. For construction sites. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hook",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconCraneAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M6 21V5M3.5 21h7M6 5h14M6 5l4-2v2M10 5l-4 4M6 13h3" />
      <path data-part="hook" d="M17 5v5M15.5 10h3l-1.5 3z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
