// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The diamond turns a quarter. For shapes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "diamond",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(90deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconDiamondAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="diamond" d="M12 3l9 9-9 9-9-9z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
