// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The rungs pulse in turn. For biology and genetics. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "rung-1",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "rung-2",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 80
    },
    {
      "part": "rung-3",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 160
    },
    {
      "part": "rung-4",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 240
    }
  ],
  "pause": 1400
};

export function IconDnaAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8 3c0 4.5 8 4.5 8 9s-8 4.5-8 9M16 3c0 4.5-8 4.5-8 9s8 4.5 8 9" />
      <path data-part="rung-1" d="M8.6 5.5h6.8" style={{ transformBox: "fill-box" }} />
      <path data-part="rung-2" d="M9.6 9.5h4.8" style={{ transformBox: "fill-box" }} />
      <path data-part="rung-3" d="M9.6 14.5h4.8" style={{ transformBox: "fill-box" }} />
      <path data-part="rung-4" d="M8.6 18.5h6.8" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
