// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The drill whirs. For power tools. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "drill",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1px)"
        },
        {
          "transform": "translateX(1px)"
        },
        {
          "transform": "translateX(-0.75px)"
        },
        {
          "transform": "translateX(0.75px)"
        },
        {
          "transform": "translateX(-0.35px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconDrillAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="drill" d="M4 6.5h11a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H4zM17 9h4M8 11.5l-1.5 8a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1L12.5 11.5M7 4v2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
