// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The drone hovers. For aerial and delivery. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "drone",
      "duration": 1200,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translateY(0px)"
        },
        {
          "transform": "translateY(-2px)"
        },
        {
          "transform": "translateY(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconDroneAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="drone" d="M14 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM10.6 10.6L7.8 7.8M13.4 10.6l2.8-2.8M10.6 13.4l-2.8 2.8M13.4 13.4l2.8 2.8M8.5 6a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM20.5 6a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM8.5 18a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM20.5 18a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
