// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The eraser rubs. For clear and erase. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "eraser",
      "duration": 760,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(-1.5px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(1px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateX(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconEraserAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8.5 20.5h12" />
      <path data-part="eraser" d="M4.9 14.9l8.5-8.5a2 2 0 0 1 2.8 0l2.9 2.9a2 2 0 0 1 0 2.8l-7.6 7.6a2 2 0 0 1-1.4.8H8.1a2 2 0 0 1-1.4-.6l-1.8-1.8a2 2 0 0 1 0-3.2zM9.5 10.5l5 5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
