// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The factory hums. For manufacturing and production. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "factory",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-0.8px)"
        },
        {
          "transform": "translateX(0.8px)"
        },
        {
          "transform": "translateX(-0.6000000000000001px)"
        },
        {
          "transform": "translateX(0.6000000000000001px)"
        },
        {
          "transform": "translateX(-0.27999999999999997px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFactoryAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3 21h18M7 17.5h2M12 17.5h2" />
      <path data-part="factory" d="M3 21V11l5 3.5V11l5 3.5V11l5 3.5V4.5h3V21z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
