// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The blades turn. For cooling and airflow. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "blades",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFanAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="blades" d="M13.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zM12 10.5c-.8-2.9.4-6.5 3.2-6.5 1.6 0 2.4 1.6 1.2 3.4L13.4 11M13.3 12.8c2.9.9 5.4 3.5 4 5.9-.8 1.3-2.6 1.2-3.8-.6l-1.6-3.6M10.7 12.6c-2.2 2-5.6 2.9-7 .5-.7-1.3.2-2.9 2.4-3.2l4.1-.4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
