// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrows run ahead in turn. For seek forward. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow-1",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "arrow-2",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 80
    }
  ],
  "pause": 1400
};

export function IconFastForwardAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="arrow-1" d="M4 6.5v11l7-5.5z" style={{ transformBox: "fill-box" }} />
      <path data-part="arrow-2" d="M13 6.5v11l7-5.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
