// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrow drops through the page. For downloads. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 5px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFileDownloadAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M6 3h8l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zM14 3v5h5" />
      <path data-part="arrow" d="M12 11.5v6M9.5 15l2.5 2.5 2.5-2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
