// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The front page slides forward. For multiple files. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "front",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1px, -1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFilesAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M5 7.5v12a1 1 0 0 0 1 1h9" />
      <path data-part="front" d="M9 3.5h7l4 4v10a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1v-13a1 1 0 0 1 1-1zM16 3.5v4h4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
