// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The brackets open. For source files. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "left",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "right",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFileCodeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M6 3h8l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zM14 3v5h5" />
      <path data-part="left" d="M10 12.5l-2 2 2 2" style={{ transformBox: "fill-box" }} />
      <path data-part="right" d="M14 12.5l2 2-2 2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
