// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The ridges draw one after another. For biometric sign-in. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "ridge-1",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "ridge-2",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 90
    },
    {
      "part": "ridge-3",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    },
    {
      "part": "ridge-4",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 270
    }
  ],
  "pause": 1400
};

export function IconFingerprintAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="ridge-1" d="M4.6 8.4a9 9 0 0 1 13.9-1.9" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="ridge-2" d="M5.8 17.3A11 11 0 0 0 7 12.3a5 5 0 0 1 8.4-3.7" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="ridge-3" d="M17.6 9.8A5 5 0 0 1 18 11.8a22 22 0 0 1-.9 6.2" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="ridge-4" d="M8.4 20.4A14 14 0 0 0 10 13.4a2 2 0 0 1 4 0c0 2.4-.4 4.8-1.2 7" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
