// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The fish swims ahead. For seafood and aquariums. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "fish",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFishAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="fish" d="M21 12c-2 3.2-5 5.5-8.5 5.5-3 0-5.4-1.6-7.3-3.8L2.5 17V7l2.7 3.3C7.1 8.1 9.5 6.5 12.5 6.5 16 6.5 19 8.8 21 12zM16 10.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
