// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The flag flutters on its pole. For report and milestones. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "cloth",
      "duration": 820,
      "easing": "linear",
      "origin": "0% 50%",
      "keyframes": [
        {
          "transform": "scaleX(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleX(0.86)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleX(1.05)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleX(0.97)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scaleX(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFlagAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M5 21V4" />
      <path data-part="cloth" d="M5 4.5h13.5L15 9.25 18.5 14H5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
