// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The flower sways. For spring and gardens. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "flower",
      "duration": 1100,
      "easing": "linear",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-8deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(6deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-3.2deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(1.2deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFlowerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="flower" d="M6 4.5l3 2 3-3 3 3 3-2V9a6 6 0 0 1-12 0zM12 15v6M12 18.5c-1.5-1.8-3.5-2.5-6-2.5.3 2 2.5 3.5 6 3.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
