// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The folder hops. For folders. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "folder",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconFolderAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="folder" d="M17.3 7.5h-5.8l-2-2.5H5A1.5 1.5 0 0 0 3.5 6.5V18A1.5 1.5 0 0 0 5 19.5h14a1.5 1.5 0 0 0 1.5-1.5v-7.3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
