// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The door lines draw. For parking and storage. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "slat-1",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "slat-2",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 100
    }
  ],
  "pause": 1400
};

export function IconGarageAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3 20.5V9l9-5.5L21 9v11.5M6.5 20.5V12h11v8.5" />
      <path data-part="slat-1" d="M6.5 15h11" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="slat-2" d="M6.5 18h11" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
