// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The needle sweeps and settles. For performance and speed. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "needle",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "0% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-70deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconGaugeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4.5 18.5a9 9 0 1 1 15 0" />
      <path data-part="needle" d="M12 13l4-4.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
