// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The gift jumps. For gifts and rewards. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "gift",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-3px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-1.0499999999999998px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconGiftAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="gift" d="M20 11.5V19a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-7.5M3.5 8h17v3.5h-17zM12 8v12M12 8S9.6 8 8.3 7.6A2.3 2.3 0 0 1 9.1 3.2C10.7 3.2 12 8 12 8zM12 8s2.4 0 3.7-.4a2.3 2.3 0 0 0-.8-4.4C13.3 3.2 12 8 12 8z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
