// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The branch draws out. For branches. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "branch",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconGitBranchAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M6 6.5v11M8.5 4a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM8.5 20a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM20.5 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
      <path data-part="branch" d="M6 12h9.5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
