// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrow brings the change back. For pull requests. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconGitPullRequestAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8.5 5.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM8.5 18.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM20.5 18.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM6 8v8" />
      <path data-part="arrow" d="M18 16V9a2 2 0 0 0-2-2h-4.5M14 4.5L11.5 7 14 9.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
