// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The globe turns on its axis. For language and region pickers. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "meridian",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scaleX(1)"
        },
        {
          "transform": "scaleX(0.08)"
        },
        {
          "transform": "scaleX(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconGlobeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3M3.5 12h17" />
      <path data-part="meridian" d="M12 3.5c2.3 2.4 3.5 5.2 3.5 8.5s-1.2 6.1-3.5 8.5c-2.3-2.4-3.5-5.2-3.5-8.5S9.7 5.9 12 3.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
