// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bars grow and the line climbs. For growth. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bar-1",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "bar-2",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 70
    },
    {
      "part": "bar-3",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 140
    },
    {
      "part": "bar-4",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 210
    },
    {
      "part": "line",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 320
    }
  ],
  "pause": 1400
};

export function IconGrowthAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3.5 20.5h17" />
      <path data-part="bar-1" d="M6 16.5v4" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-2" d="M10.5 13v7.5" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-3" d="M15 10v10.5" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-4" d="M19.5 6v14.5" style={{ transformBox: "fill-box" }} />
      <path data-part="line" d="M5 12l4.5-4 4 2.5L20 4M16 4h4v4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
