// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The heart beats twice. For health and favourites. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "heart",
      "duration": 820,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.16)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconHeartBeatAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="heart" d="M12 20.5S3.5 15 3.5 9A4.5 4.5 0 0 1 12 6.5 4.5 4.5 0 0 1 20.5 9c0 6-8.5 11.5-8.5 11.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
