// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hexagon turns a sixth. For shapes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hexagon",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(60deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconHexagonAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="hexagon" d="M12 3l7.8 4.5v9L12 21l-7.8-4.5v-9z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
