// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The ring turns back once. For history and recent. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "ring",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(-360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconHistoryAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 7.5V12l3.5 2" />
      <path data-part="ring" d="M3.5 12a8.5 8.5 0 1 0 2.6-6.1M3.5 5.5V10h4.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
