// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hourglass turns over. For waiting and pending. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "glass",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(180deg)"
        }
      ]
    }
  ],
  "pause": 900
};

export function IconHourglassAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="glass" d="M6.5 3.5h11M6.5 20.5h11M7.5 3.5v2.3a4 4 0 0 0 1.6 3.2L12 12l2.9-3a4 4 0 0 0 1.6-3.2V3.5M7.5 20.5v-2.3a4 4 0 0 1 1.6-3.2L12 12l2.9 3a4 4 0 0 1 1.6 3.2v2.3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
