// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The details write themselves on the card. For identity. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "line-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 120
    }
  ],
  "pause": 1400
};

export function IconIdCardAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 5H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.2M9.5 11a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM5 16a3 3 0 0 1 5 0" />
      <path data-part="line-1" d="M13 10h5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-2" d="M13 13.5h4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
