// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The landscape draws. For images. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hills",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "sun",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 300
    }
  ],
  "pause": 1400
};

export function IconImageAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.2" />
      <path data-part="hills" d="M3 16l5-5 4 4 3-3 6 6" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="sun" d="M15.5 8.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
