// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The tray bounces. For inboxes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tray",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconInboxAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="tray" d="M3 12.5V19a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-6.5M3 12.5h5l1.5 3h5l1.5-3h5M3 12.5L6 5h12l3 7.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
