// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The key turns. For API keys and access. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "key",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "20% 80%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-25deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconKeyAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="key" d="M11.5 16a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zM10.5 13.5L20 4M16.5 7.5l2.5 2.5M14 10l2 2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
