// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The rungs draw upwards. For climbing and levels. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "rung-1",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "rung-2",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 90
    },
    {
      "part": "rung-3",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconLadderAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 3v18M17 3v18" />
      <path data-part="rung-1" d="M7 17h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="rung-2" d="M7 12h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="rung-3" d="M7 7h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
