// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The characters swap places. For translation. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "latin",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-1px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "other",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLanguageAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="latin" d="M13 20.5l4-9.5 4 9.5M14.3 17.5h5.4" style={{ transformBox: "fill-box" }} />
      <path data-part="other" d="M3.5 5.5h9M8 3.5v2M10.5 5.5c-.8 3.5-3 6.2-6.5 8M6.5 8.5c1.1 2 2.8 3.6 5 4.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
