// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lid opens. For laptops. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "lid",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLaptopAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M2.5 19h19" />
      <path data-part="lid" d="M16.8 5H6a2 2 0 0 0-2 2v9h16V8.2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
