// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The layers lift apart. For stacks and layers. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "top",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "middle",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLayersAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3 16.5L12 21l9-4.5" />
      <path data-part="top" d="M12 3l9 4.5-9 4.5-9-4.5z" style={{ transformBox: "fill-box" }} />
      <path data-part="middle" d="M3 12l9 4.5 9-4.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
