// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The leaf sways. For eco and sustainable. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "leaf",
      "duration": 1100,
      "easing": "linear",
      "origin": "0% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-10deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(7.5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-4deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(1.5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLeafAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="leaf" d="M5 20C5 11 10 5 20 4c-.5 10-6.5 15.5-15 16zM5 20l7.5-7.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
