// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lemon rolls a little. For citrus and fresh. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "lemon",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(15deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLemonAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="lemon" d="M5.5 18.5c-1.5-1.5-1.3-3.6-.6-5.6 1.4-4.3 5.7-8.3 10.1-8.8 1.6-.2 2.8 0 3.9.9.9 1.1 1.1 2.3.9 3.9-.5 4.4-4.5 8.7-8.8 10.1-2 .7-4.1.9-5.5-.5zM5.5 18.5L4 20M18.9 5.1L20 4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
