// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The links pull together. For copy link and attach URL. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "left",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1px, -1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "right",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-1px, 1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconLinkAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="left" d="M10 13.5a4 4 0 0 0 6 .4l3-3a4 4 0 0 0-5.66-5.66L12 6.6" style={{ transformBox: "fill-box" }} />
      <path data-part="right" d="M14 10.5a4 4 0 0 0-6-.4l-3 3a4 4 0 0 0 5.66 5.66L12 17.4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
