// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lines draw in order. For numbered lists. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line-1",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "line-2",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 90
    },
    {
      "part": "line-3",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconListOrderedAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4.3 5.6l1.2-.6v4.5M4 10h3M4 14.2a1.3 1.3 0 1 1 2.2 1L4 18.6h3.2" />
      <path data-part="line-1" d="M10 6.5h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-2" d="M10 12h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-3" d="M10 17.5h10" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
