// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The ticks draw in turn. For checklists. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tick-1",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "tick-2",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 110
    },
    {
      "part": "tick-3",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 220
    }
  ],
  "pause": 1400
};

export function IconListChecksAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M11 6.5h9M11 12h9M11 17.5h9" />
      <path data-part="tick-1" d="M3.5 6.5l1.5 1.5 2.5-3" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="tick-2" d="M3.5 12l1.5 1.5 2.5-3" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="tick-3" d="M3.5 17.5l1.5 1.5 2.5-3" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
