// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lens glints. For inspecting detail. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "glint",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMagnifierAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M15.5 10.5a5 5 0 1 1-10 0 5 5 0 0 1 10 0zM14 14l6.5 6.5" />
      <path data-part="glint" d="M8.5 9a2 2 0 0 1 2-2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
