// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The folded map sways. For maps and directions. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "map",
      "duration": 620,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-6deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(4.800000000000001deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-3deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(1.5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMapAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="map" d="M9 4L3.5 6.5v13L9 17l6 3 5.5-2.5v-13L15 7zM9 4v13M15 7v13" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
