// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The medal swings on its ribbon. For rewards. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "medal",
      "duration": 900,
      "easing": "linear",
      "origin": "50% 0%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(10deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-7.800000000000001deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(5deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-2.2deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMedalAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="medal" d="M8.5 3.5l2.5 6M15.5 3.5l-2.5 6M17 15a5 5 0 1 1-10 0 5 5 0 0 1 10 0zM12 13v4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
