// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lines write themselves in the bubble. For comments. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "line-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 120
    }
  ],
  "pause": 1400
};

export function IconMessageTextAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 4H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h3v3.5l4.5-3.5H19a2 2 0 0 0 2-2V7.2" />
      <path data-part="line-1" d="M7.5 9h9" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-2" d="M7.5 12.5h6" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
