// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The microphone pulses. For voice input. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "capsule",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMicAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21" />
      <path data-part="capsule" d="M9 6a3 3 0 0 1 6 0v5a3 3 0 0 1-6 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
