// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The line draws across. For remove and decrease. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMinusAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="line" d="M5 12h14" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
