// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The dots hop in a wave. For overflow menus. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "dot-1",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    },
    {
      "part": "dot-2",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 90
    },
    {
      "part": "dot-3",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconMoreHorizontalAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="dot-1" d="M5 12a1 1 0 1 0 2 0 1 1 0 1 0-2 0" style={{ transformBox: "fill-box" }} />
      <path data-part="dot-2" d="M11 12a1 1 0 1 0 2 0 1 1 0 1 0-2 0" style={{ transformBox: "fill-box" }} />
      <path data-part="dot-3" d="M17 12a1 1 0 1 0 2 0 1 1 0 1 0-2 0" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
