// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The wheel scrolls. For scroll hints. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wheel",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 2px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(0px, -2px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconMouseAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 3a6 6 0 0 1 6 6v6a6 6 0 0 1-12 0V9a6 6 0 0 1 6-6z" />
      <path data-part="wheel" d="M12 7v3.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
