// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrow launches forward. For directions and live location. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconNavigationAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="arrow" d="M4 11l16-7-7 16-2-7z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
