// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The notebook tilts. For notes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "book",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-8deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconNotebookAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="book" d="M6 3.5h12a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-15a1 1 0 0 1 1-1zM9 3.5v17M3.5 7.5H5M3.5 12H5M3.5 16.5H5M12 8h4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
