// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The satellite circles. For orbits and cycles. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "orbit",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconOrbitAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M14 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" />
      <path data-part="orbit" d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3M18.5 5.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
