// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The toes pop in turn. For pets. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "toe-1",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    },
    {
      "part": "toe-2",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 70
    },
    {
      "part": "toe-3",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 140
    },
    {
      "part": "toe-4",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ],
      "delay": 210
    }
  ],
  "pause": 1400
};

export function IconPawAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 13c-2.8 0-5 2.8-5 5 0 1.4 1 2 2.3 2 1 0 1.7-.5 2.7-.5s1.7.5 2.7.5c1.3 0 2.3-.6 2.3-2 0-2.2-2.2-5-5-5z" />
      <path data-part="toe-1" d="M7 10.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" style={{ transformBox: "fill-box" }} />
      <path data-part="toe-2" d="M11 6.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" style={{ transformBox: "fill-box" }} />
      <path data-part="toe-3" d="M16 6.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" style={{ transformBox: "fill-box" }} />
      <path data-part="toe-4" d="M20 10.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
