// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The phone rings and the waves appear. For incoming calls. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "phone",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1.6px)"
        },
        {
          "transform": "translateX(1.6px)"
        },
        {
          "transform": "translateX(-1.2000000000000002px)"
        },
        {
          "transform": "translateX(1.2000000000000002px)"
        },
        {
          "transform": "translateX(-0.5599999999999999px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    },
    {
      "part": "wave-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 100
    },
    {
      "part": "wave-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 210
    }
  ],
  "pause": 1400
};

export function IconPhoneCallAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="phone" d="M8.6 3.5H6A2.5 2.5 0 0 0 3.5 6c0 8 6.5 14.5 14.5 14.5a2.5 2.5 0 0 0 2.5-2.5v-2.6l-4.4-1.8-1.9 2.2a11 11 0 0 1-5.9-5.9l2.2-1.9z" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-1" d="M14.5 7a2.5 2.5 0 0 1 2.5 2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-2" d="M14.5 3.5a6 6 0 0 1 6 6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
