// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The slice pops out. For share and breakdowns. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "slice",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1px, -1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPieChartAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M11.5 4.5a8 8 0 1 0 8 8h-8z" />
      <path data-part="slice" d="M13 3a8 8 0 0 1 8 8h-8z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
