// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The pig hops. For savings. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "pig",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-2px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-0.7px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPiggyBankAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="pig" d="M5 11.5c0-3.3 3.1-6 7-6 2.6 0 4.9 1.2 6.1 3H20v4h-1.2c-.4 1.3-1.3 2.5-2.3 3.3V19h-3v-1.6a8.5 8.5 0 0 1-3 0V19h-3v-2.5C5.9 15.3 5 13.5 5 11.5zM15.5 10h.01M10 8.5h3M5 11.5c-1.2 0-2-.8-2-2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
