// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The pill turns. For medicine. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "pill",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(180deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPillAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="pill" d="M10.5 20.5l10-10a4.95 4.95 0 0 0-7-7l-10 10a4.95 4.95 0 0 0 7 7zM8.5 8.5l7 7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
