// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The pin drops onto the map. For locations and addresses. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "pin",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-3px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(-1.0499999999999998px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "translateY(0px)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPinAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="pin" d="M17.89 7.25A6.5 6.5 0 0 1 18.5 10c0 5.5-6.5 11-6.5 11S5.5 15.5 5.5 10a6.5 6.5 0 0 1 9.25-5.89M14 10a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
