// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The pipette dips. For colour picking. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "pipette",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-1px, 1px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPipetteAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="pipette" d="M14 6l4 4M17.5 3.5a2.1 2.1 0 0 1 3 3l-3 3-3-3zM14.5 6.5l-9 9V19H9l9-9" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
