// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plane climbs. For flights. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plane",
      "duration": 1200,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translateY(0px)"
        },
        {
          "transform": "translateY(-2.5px)"
        },
        {
          "transform": "translateY(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPlaneAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="plane" d="M12 3c1 0 1.5 1 1.5 2.5V9l7 4v2l-7-2v4.5l2.5 2V21L12 20l-4 1v-1.5l2.5-2V13l-7 2v-2l7-4V5.5C10.5 4 11 3 12 3z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
