// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The planet tilts in its ring. For space and worlds. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "planet",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(12deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPlanetAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="planet" d="M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0zM7.6 14.4C4.8 15.9 3 17.6 3.6 18.6c.8 1.4 5.3.2 10-2.5s7.9-6.2 7.1-7.6c-.6-1-3-.8-5.9.4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
