// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plug pushes in. For integrations. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plug",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPlugAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 16.5V21" />
      <path data-part="plug" d="M9 3v5M15 3v5M6.5 8h11v3a5.5 5.5 0 0 1-11 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
