// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plus turns a quarter inside its ring. For add actions. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plus",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(90deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPlusCircleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3" />
      <path data-part="plus" d="M12 8.5v7M8.5 12h7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
