// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The waves spread around the mic. For podcasts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wave-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "wave-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 120
    }
  ],
  "pause": 1400
};

export function IconPodcastAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M13.5 11a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zM11 15.5h2l-.5 5h-1z" />
      <path data-part="wave-1" d="M7.5 15.5a6 6 0 1 1 9 0" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-2" d="M4.8 17.8a9.5 9.5 0 1 1 14.4 0" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
