// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The piece wiggles into place. For plugins. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "piece",
      "duration": 620,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-8deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(6.4deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(-4deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(2deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "rotate(0deg)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconPuzzleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="piece" d="M10 4.5a2 2 0 0 1 4 0V6h4a1 1 0 0 1 1 1v4h-1.5a2 2 0 0 0 0 4H19v4a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-4h1.5a2 2 0 0 0 0-4H5V7a1 1 0 0 1 1-1h4z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
