// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The symbol turns. For hazards and warnings. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "blades",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(120deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconRadiationAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M13.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
      <path data-part="blades" d="M9.5 12H4a8 8 0 0 1 4-6.9l2.7 4.7M14.5 12H20a8 8 0 0 0-4-6.9l-2.7 4.7M10.7 13.3L8 18a8 8 0 0 0 8 0l-2.7-4.7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
