// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arcs draw in turn. For colour and pride. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arc-1",
      "duration": 480,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "arc-2",
      "duration": 480,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 110
    },
    {
      "part": "arc-3",
      "duration": 480,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 220
    }
  ],
  "pause": 1400
};

export function IconRainbowAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="arc-1" d="M3 17a9 9 0 0 1 18 0" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="arc-2" d="M6.5 17a5.5 5.5 0 0 1 11 0" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="arc-3" d="M10 17a2 2 0 0 1 4 0" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
