// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The two arrows run their loop. For repeat and subscriptions. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "top",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "bottom",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(-2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconRepeatAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="top" d="M4 9.5A3.5 3.5 0 0 1 7.5 6H20M17 3l3 3-3 3" style={{ transformBox: "fill-box" }} />
      <path data-part="bottom" d="M20 14.5a3.5 3.5 0 0 1-3.5 3.5H4M7 21l-3-3 3-3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
