// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The arrow turns a full circle backwards. For reset and restore. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "ring",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(-360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconRotateCcwAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="ring" d="M4 12a8 8 0 1 0 2.34-5.66M6.34 2.84v3.5h3.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
