// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The marks draw along the ruler. For measuring. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "mark-1",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "mark-2",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 90
    },
    {
      "part": "mark-3",
      "duration": 260,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 180
    }
  ],
  "pause": 1400
};

export function IconRulerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3.5 16.5l13-13 4 4-13 13z" />
      <path data-part="mark-1" d="M7 13l2 2" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="mark-2" d="M10 10l2 2" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="mark-3" d="M13 7l2 2" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
