// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The blades snip. For cut and trim. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "blade-a",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "0% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(7deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    },
    {
      "part": "blade-b",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "0% 0%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-7deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconScissorsAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M9 6.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0zM9 17.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
      <path data-part="blade-a" d="M8.6 8L20 18.5" style={{ transformBox: "fill-box" }} />
      <path data-part="blade-b" d="M8.6 16L20 5.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
