// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plane flies out and back in. For sending in tight spots. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plane",
      "duration": 680,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1,
          "easing": "cubic-bezier(0.4, 0, 1, 1)"
        },
        {
          "offset": 0.42,
          "transform": "translate(5px, -5px)",
          "opacity": 0
        },
        {
          "offset": 0.43,
          "transform": "translate(-5px, 5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translate(0px, 0px)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSendFlyAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="plane" d="M21 3L10.5 13.5M21 3l-6.5 18-4-7.5L3 9.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
