// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lights blink in turn. For servers and infrastructure. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "led-1",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    },
    {
      "part": "led-2",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ],
      "delay": 160
    }
  ],
  "pause": 1400
};

export function IconServerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 3H5a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5.2M17.8 14H5a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-2.8" />
      <path data-part="led-1" d="M6.5 6.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="led-2" d="M6.5 17.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
