// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The tick draws on the shield. For protected. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tick",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconShieldCheckAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 3l7 2.5V11c0 4.5-3 8-7 10-4-2-7-5.5-7-10V5.5z" />
      <path data-part="tick" d="M9 12l2 2 4-4.5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
