// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The shovel digs. For gardening and digging. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "shovel",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "70% 30%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(14deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconShovelAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="shovel" d="M14 10l6-6M18.5 2.5l3 3M14 10l-4.5-1-5 5a2 2 0 0 0 0 2.8l1.7 1.7a2 2 0 0 0 2.8 0l5-5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
