// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The water falls in turn. For bathrooms. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "drop-1",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "drop-2",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 60
    },
    {
      "part": "drop-3",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 120
    },
    {
      "part": "drop-4",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 180
    },
    {
      "part": "drop-5",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, 1.5px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 240
    }
  ],
  "pause": 1400
};

export function IconShowerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M5 21V7a3.5 3.5 0 0 1 7 0v1M9 11.5a3 3 0 0 1 6 0z" />
      <path data-part="drop-1" d="M10 14.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-2" d="M12 15.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-3" d="M14 14.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-4" d="M11 18h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="drop-5" d="M13 18h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
