// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The crossing lines push their arrows out. For shuffle and random. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "heads",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconShuffleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3 7h3.5c5 0 6 10 11 10H21M3 17h3.5c1.5 0 2.6-.9 3.5-2.2M13.9 9.2C14.8 7.9 15.9 7 17.5 7H21" />
      <path data-part="heads" d="M18 14l3 3-3 3M18 4l3 3-3 3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
