// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The inspector divider slides. For toggling a right panel. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "divider",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSidebarRightAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.2" />
      <path data-part="divider" d="M15 3v18" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
