// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bars rise one by one. For strength and levels. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bar-1",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    },
    {
      "part": "bar-2",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 80
    },
    {
      "part": "bar-3",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 160
    },
    {
      "part": "bar-4",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ],
      "delay": 240
    }
  ],
  "pause": 1400
};

export function IconSignalAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="bar-1" d="M5 20v-3" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-2" d="M10 20v-7" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-3" d="M15 20V9" style={{ transformBox: "fill-box" }} />
      <path data-part="bar-4" d="M20 20V4" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
