// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The branches draw from the root. For site structure and org charts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "links",
      "duration": 520,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "node-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 360
    },
    {
      "part": "node-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 450
    }
  ],
  "pause": 1400
};

export function IconSitemapAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M9.5 3.5h5v5h-5z" />
      <path data-part="links" d="M12 8.5v3.5M6 15.5V12h12v3.5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="node-1" d="M3.5 15.5h5v5h-5z" style={{ transformBox: "fill-box" }} />
      <path data-part="node-2" d="M15.5 15.5h5v5h-5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
