// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The panel catches the light. For solar and energy. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "panel",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSolarPanelAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 14v4M8 20.5h8" />
      <path data-part="panel" d="M4.5 4h15l2 10h-19zM3.5 9h17M9 4l-1 10M15 4l1 10" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
