// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The steam rises. For hot meals and lunch. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "steam-1",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "steam-2",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ],
      "delay": 100
    },
    {
      "part": "steam-3",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ],
      "delay": 200
    }
  ],
  "pause": 1400
};

export function IconSoupAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3.5 11h17a8.5 8.5 0 0 1-17 0zM8 20.5h8" />
      <path data-part="steam-1" d="M9 7.5c-.8-.9-.8-2.1 0-3" style={{ transformBox: "fill-box" }} />
      <path data-part="steam-2" d="M12.5 7.5c-.8-.9-.8-2.1 0-3" style={{ transformBox: "fill-box" }} />
      <path data-part="steam-3" d="M16 7.5c-.8-.9-.8-2.1 0-3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
