// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bubble finds the middle. For alignment. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bubble",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSpiritLevelAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M3 9h18v6H3zM10 9v6M14 9v6M6 12h1.5M16.5 12H18" />
      <path data-part="bubble" d="M12 11.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
