// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The curve draws between its handles. For vector paths. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "curve",
      "duration": 700,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSplineAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M6.5 19a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zM20.5 5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
      <path data-part="curve" d="M5 17.5C5 10 19 14 19 6.5" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
