// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The spray mists out. For paint and graffiti. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "mist-1",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    },
    {
      "part": "mist-2",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ],
      "delay": 50
    },
    {
      "part": "mist-3",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ],
      "delay": 100
    },
    {
      "part": "mist-4",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ],
      "delay": 150
    }
  ],
  "pause": 1400
};

export function IconSprayCanAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7 9.5h7v10a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1zM8.5 9.5V7h4v2.5M9.5 7V5h2v2" />
      <path data-part="mist-1" d="M15.5 4h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="mist-2" d="M18 3h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="mist-3" d="M18 5.5h.01" style={{ transformBox: "fill-box" }} />
      <path data-part="mist-4" d="M20.5 4.5h.01" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
