// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The sprout grows. For growth and new starts. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plant",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSproutAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M7.5 20.5h9" />
      <path data-part="plant" d="M12 20.5V11M12 11c0-3.5-2.5-6-6.5-6 0 3.7 2.6 6 6.5 6zM12 13.5c0-3.2 2.4-5.5 6.5-5.5 0 3.4-2.5 5.5-6.5 5.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
