// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The square turns a quarter. For shapes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "square",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(90deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSquareAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="square" d="M17.3 3.5H5.5a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2V6.7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
