// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The captions write themselves. For subtitles. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "line-1",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "line-2",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 80
    },
    {
      "part": "line-3",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 160
    },
    {
      "part": "line-4",
      "duration": 300,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 240
    }
  ],
  "pause": 1400
};

export function IconSubtitlesAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 5H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.2" />
      <path data-part="line-1" d="M7 12h4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-2" d="M13 12h4" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-3" d="M7 15.5h7" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="line-4" d="M16 15.5h1" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
