// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The sun comes up. For mornings. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "arrow",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(0px, -2px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconSunriseAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 17.5a8 8 0 0 1 16 0M2.5 20.5h19M4.5 11.5l1.3 1M19.5 11.5l-1.3 1" />
      <path data-part="arrow" d="M12 3v5M9 6l3-3 3 3" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
