// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The tablet tilts. For tablets. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tablet",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-10deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconTabletAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="tablet" d="M16.8 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6.2M11 18h2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
