// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The steam rises. For tea, breaks and cafes. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "steam-1",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ]
    },
    {
      "part": "steam-2",
      "duration": 900,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateY(0px)",
          "opacity": 1,
          "easing": "ease-in"
        },
        {
          "offset": 0.5,
          "transform": "translateY(-2.5px)",
          "opacity": 0
        },
        {
          "offset": 0.51,
          "transform": "translateY(1.5px)",
          "opacity": 0,
          "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)"
        },
        {
          "transform": "translateY(0px)",
          "opacity": 1
        }
      ],
      "delay": 120
    }
  ],
  "pause": 1400
};

export function IconTeacupAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 10h12v3.5a6 6 0 0 1-6 6 6 6 0 0 1-6-6zM16 11.5h1.5a2.5 2.5 0 0 1 0 5h-2.2M3 21.5h14" />
      <path data-part="steam-1" d="M8 3.5c-.7.8-.7 1.7 0 2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="steam-2" d="M11.5 3.5c-.7.8-.7 1.7 0 2.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
