// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The tube tilts to the sky. For astronomy and discovery. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "tube",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "40% 70%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-8deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconTelescopeAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M11 14.5l-3 6.5M12.5 14l3 6.5M5.5 18l-1-2.5" />
      <path data-part="tube" d="M3.5 13.5l13-6 2 4.5-13 6zM16.5 7.5l3-1.5 2 4.5-3 1.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
