// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cursor blinks. For consoles and CLIs. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "cursor",
      "duration": 900,
      "easing": "steps(2, jump-none)",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0
        },
        {
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 0
};

export function IconTerminalAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M17.8 4H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V7.2M7 9l3 3-3 3" />
      <path data-part="cursor" d="M12.5 15h4.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
