// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The mercury rises. For temperature. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "mercury",
      "duration": 560,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "scaleY(0.2)"
        },
        {
          "transform": "scaleY(1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconThermometerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M14 14.8V5a2 2 0 0 0-4 0v9.8a4 4 0 1 0 4 0z" />
      <path data-part="mercury" d="M12 11v6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
