// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The thumb tips down. For dislike and not helpful. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "thumb",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "100% 0%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-14deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconThumbsDownAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="thumb" d="M17 13.5V3.5h2.5a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1zM17 13.5l-4 7.5a2 2 0 0 1-2-2v-3.5H5.8a2 2 0 0 1-2-2.35l1.1-6a2 2 0 0 1 2-1.65H17" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
