// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hand sweeps a full turn. For timers and countdowns. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hand",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 200
};

export function IconTimerAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M18.8 10.33A7.5 7.5 0 1 1 15.17 6.7M10 2.5h4M18.5 6.5L20 5" />
      <path data-part="hand" d="M12 13.5V10" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
