// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The knob slides and returns. For switch settings. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "knob",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(3px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconToggleLeftAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M16 7H8a5 5 0 0 0 0 10h8a5 5 0 0 0 0-10z" />
      <path data-part="knob" d="M10.5 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
