// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The minus draws. For remove member. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "minus",
      "duration": 400,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconUserMinusAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M14.5 7.5a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM3 20.5v-1A5.5 5.5 0 0 1 8.5 14h3.2" />
      <path data-part="minus" d="M15 17.5h6" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
