// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The lens pulses. For video calls. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "lens",
      "duration": 760,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "opacity": 1
        },
        {
          "transform": "scale(1.14)",
          "opacity": 0.55
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconVideoAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M11.8 6H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V9.2" />
      <path data-part="lens" d="M15 10.5l6-3.5v10l-6-3.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
