// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The virus turns. For health and infection. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "virus",
      "duration": 520,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(90deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconVirusAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="virus" d="M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0zM12 7V4M12 20v-3M7 12H4M20 12h-3M8.5 8.5L6.4 6.4M17.6 17.6l-2.1-2.1M8.5 15.5l-2.1 2.1M17.6 6.4l-2.1 2.1M11 3.5h2M11 20.5h2M3.5 11v2M20.5 11v2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
