// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The wave reaches out. For low volume. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wave",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconVolumeLowAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 9.5v5h3.5l4.5 4v-13l-4.5 4z" />
      <path data-part="wave" d="M15.5 9a4 4 0 0 1 0 6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
