// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cross shakes. For muted. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "cross",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1.6px)"
        },
        {
          "transform": "translateX(1.6px)"
        },
        {
          "transform": "translateX(-1.2000000000000002px)"
        },
        {
          "transform": "translateX(1.2000000000000002px)"
        },
        {
          "transform": "translateX(-0.5599999999999999px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconVolumeOffAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M4 9.5v5h3.5l4.5 4v-13l-4.5 4z" />
      <path data-part="cross" d="M16 9.5l5 5M21 9.5l-5 5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
