// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The wand flicks and the sparks appear. For magic and AI actions. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wand",
      "duration": 620,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "0% 100%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "offset": 0.45,
          "transform": "rotate(-10deg)"
        },
        {
          "transform": "rotate(0deg)"
        }
      ]
    },
    {
      "part": "spark-1",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 180
    },
    {
      "part": "spark-2",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 270
    },
    {
      "part": "spark-3",
      "duration": 420,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(0.6)",
          "opacity": 0
        },
        {
          "transform": "scale(1)",
          "opacity": 1
        }
      ],
      "delay": 360
    }
  ],
  "pause": 1400
};

export function IconWandAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="wand" d="M4 20L14.5 9.5M12.5 7.5l4 4" style={{ transformBox: "fill-box" }} />
      <path data-part="spark-1" d="M18 3v4M16 5h4" style={{ transformBox: "fill-box" }} />
      <path data-part="spark-2" d="M20 11v2M19 12h2" style={{ transformBox: "fill-box" }} />
      <path data-part="spark-3" d="M11 3v2M10 4h2" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
