// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The drum spins. For laundry. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "drum",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconWashingMachineAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M16.3 3H6.5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V6.2M4.5 7.5h15M7.5 5.25h.01M10 5.25h.01" />
      <path data-part="drum" d="M16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
