// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The hand turns. For wearables and time. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "hand",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "0% 62%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconWatchAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M8 6l.8-3h6.4l.8 3M8 18l.8 3h6.4l.8-3M18 12a6 6 0 1 1-12 0 6 6 0 0 1 12 0z" />
      <path data-part="hand" d="M12 9.5V12l1.5 1.5" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
