// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The waves roll. For sea and flow. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "wave-1",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "wave-2",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 120
    },
    {
      "part": "wave-3",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(1.5px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 240
    }
  ],
  "pause": 1400
};

export function IconWavesAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="wave-1" d="M3 7q1.5 -2 3 0t3 0q1.5 2 3 0t3 0q1.5 -2 3 0t3 0" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-2" d="M3 12q1.5 -2 3 0t3 0q1.5 2 3 0t3 0q1.5 -2 3 0t3 0" style={{ transformBox: "fill-box" }} />
      <path data-part="wave-3" d="M3 17q1.5 -2 3 0t3 0q1.5 2 3 0t3 0q1.5 -2 3 0t3 0" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
