// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The crossed signal shakes. For offline. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "signal",
      "duration": 520,
      "easing": "linear",
      "keyframes": [
        {
          "transform": "translateX(0px)"
        },
        {
          "transform": "translateX(-1.6px)"
        },
        {
          "transform": "translateX(1.6px)"
        },
        {
          "transform": "translateX(-1.2000000000000002px)"
        },
        {
          "transform": "translateX(1.2000000000000002px)"
        },
        {
          "transform": "translateX(-0.5599999999999999px)"
        },
        {
          "transform": "translateX(0px)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconWifiOffAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="signal" d="M3.5 9.4a13 13 0 0 1 4.4-2.7M12.8 6.6a13 13 0 0 1 7.7 2.8M17.4 13a8.5 8.5 0 0 0-2.7-1.7M6.6 13a8.5 8.5 0 0 1 2.2-1.4M9.6 16.5a4 4 0 0 1 4.3-.5M12 20h.01M3.5 3.5l17 17" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
