// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The gusts blow in turn. For wind. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "gust-1",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ]
    },
    {
      "part": "gust-2",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 110
    },
    {
      "part": "gust-3",
      "duration": 560,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "keyframes": [
        {
          "transform": "translate(0px, 0px)"
        },
        {
          "offset": 0.42,
          "transform": "translate(2px, 0px)"
        },
        {
          "transform": "translate(0px, 0px)"
        }
      ],
      "delay": 220
    }
  ],
  "pause": 1400
};

export function IconWindAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="gust-1" d="M3 8.5h10a2.5 2.5 0 1 0-2.5-2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="gust-2" d="M3 12.5h15a2.5 2.5 0 1 1-2.5 2.5" style={{ transformBox: "fill-box" }} />
      <path data-part="gust-3" d="M3 16.5h7" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
