// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The blades turn. For wind energy. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "blades",
      "duration": 864,
      "easing": "cubic-bezier(0.45, 0, 0.55, 1)",
      "origin": "50% 66%",
      "keyframes": [
        {
          "transform": "rotate(0deg)"
        },
        {
          "transform": "rotate(360deg)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconWindTurbineAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M12 10.5V21M9 21h6" />
      <path data-part="blades" d="M12 10.5L12 3M12 10.5l6.5 3.8M12 10.5l-6.5 3.8M13.5 10.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
