// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The cross draws inside its ring. For failed and cancelled. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "stroke-1",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ]
    },
    {
      "part": "stroke-2",
      "duration": 360,
      "easing": "cubic-bezier(0.2, 0.7, 0.2, 1)",
      "keyframes": [
        {
          "strokeDashoffset": 1
        },
        {
          "strokeDashoffset": 0
        }
      ],
      "delay": 140
    }
  ],
  "pause": 1400
};

export function IconXCircleAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M19.7 8.41A8.5 8.5 0 1 1 15.59 4.3" />
      <path data-part="stroke-1" d="M9 9l6 6" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
      <path data-part="stroke-2" d="M15 9l-6 6" pathLength={1} strokeDasharray={1} style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
