// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The bolt flickers. For instant, fast and power features. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "bolt",
      "duration": 720,
      "easing": "linear",
      "keyframes": [
        {
          "opacity": 1
        },
        {
          "opacity": 0.15
        },
        {
          "opacity": 1
        },
        {
          "opacity": 0.4
        },
        {
          "opacity": 1
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconZapAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path data-part="bolt" d="M13 3L5 13.5h6.5L11 21l8-10.5h-6.5z" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
