// Generated by scripts/icons/generate-animated.mjs from scripts/icons/animated-icons.mjs. Edit the spec, not this file.
import { AnimatedGlyph, type AnimatedIconProps, type IconMotion } from "@rhs-ui/icons/animated-icon";

/** The plus grows inside the lens. For zoom in. */
const motion: IconMotion = {
  "steps": [
    {
      "part": "plus",
      "duration": 560,
      "easing": "linear",
      "origin": "50% 50%",
      "keyframes": [
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.3)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(0.94)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1.03)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        },
        {
          "transform": "scale(1)",
          "easing": "cubic-bezier(0.45, 0, 0.55, 1)"
        }
      ]
    }
  ],
  "pause": 1400
};

export function IconZoomInAnimated(props: AnimatedIconProps) {
  return (
    <AnimatedGlyph motion={motion} {...props}>
      <path d="M16.78 8.82A6.5 6.5 0 1 1 13.55 4.9M20 20l-4.6-4.6" />
      <path data-part="plus" d="M7.5 10.5h6M10.5 7.5v6" style={{ transformBox: "fill-box" }} />
    </AnimatedGlyph>
  );
}
